#include "pch.h"
#include "Lang.h"
#include "resource.h"

#include <map>

namespace Lang {

namespace {

Id g_lang = Id::English;

struct Entry { LPCTSTR en; LPCTSTR uk; };

// ---------------------------------------------------------------------------
// UI strings. Format specifiers must be kept in the translation.
// ---------------------------------------------------------------------------
const Entry kStrings[] = {
    // Tabs / menu
    { _T("Radar"), _T("Радар") },
    { _T("Scope"), _T("Осцилограф") },
    { _T("Communication"), _T("Зв'язок") },
    { _T("Settings"), _T("Налаштування") },
    { _T("Trace"), _T("Трасування МК") },
    { _T("&File"), _T("&Файл") },
    { _T("&Open replay...\tCtrl+O"), _T("&Відкрити запис...\tCtrl+O") },
    { _T("&Close replay"), _T("&Закрити запис") },
    { _T("Start/stop &recording\tR"), _T("Почати/зупинити &запис\tR") },
    { _T("&Save frame as CSV...\tCtrl+S"), _T("З&берегти кадр як CSV...\tCtrl+S") },
    { _T("Export &targets as CSV..."), _T("Експорт &цілей у CSV...") },
    { _T("Export IF signal as &WAV..."), _T("Експорт сигналу биття у &WAV...") },
    { _T("Save screenshot as &PNG...\tF12"), _T("Зберегти знімок екрана як &PNG...\tF12") },
    { _T("E&xit"), _T("Ви&хід") },
    { _T("&Acquisition"), _T("&Захоплення") },
    { _T("&Connect / Disconnect\tF5"), _T("&Підключити / Відключити\tF5") },
    { _T("&Start\tSpace"), _T("&Старт\tПробіл") },
    { _T("S&top\tSpace"), _T("С&топ\tПробіл") },
    { _T("&Trigger\tT"), _T("&Одиночне захоплення\tT") },
    { _T("&Abort"), _T("&Перервати") },
    { _T("&Hold / Live\tH"), _T("&Зафіксувати / Наживо\tH") },
    { _T("&Reset averages\tA"), _T("С&кинути накопичення\tA") },
    { _T("&Ping"), _T("&Ping") },
    { _T("Get &status"), _T("Отримати &статус") },
    { _T("&View"), _T("&Вигляд") },
    { _T("&Radar\tCtrl+1"), _T("&Радар\tCtrl+1") },
    { _T("&Scope\tCtrl+2"), _T("&Осцилограф\tCtrl+2") },
    { _T("&Communication\tCtrl+3"), _T("&Зв'язок\tCtrl+3") },
    { _T("S&ettings\tCtrl+4"), _T("&Налаштування\tCtrl+4") },
    { _T("&Trace\tCtrl+5"), _T("&Трасування МК\tCtrl+5") },
    { _T("&Dark theme"), _T("&Темна тема") },
    { _T("&Help"), _T("&Довідка") },
    { _T("&Keyboard shortcuts"), _T("&Гарячі клавіші") },
    { _T("&About FastAcq"), _T("&Про FastAcq") },

    // Command panel
    { _T("Connect"), _T("Підключити") },
    { _T("Disconnect"), _T("Відключити") },
    { _T("Start"), _T("Старт") },
    { _T("Stop"), _T("Стоп") },
    { _T("Trigger"), _T("Одиночне") },
    { _T("Abort"), _T("Перервати") },
    { _T("Hold"), _T("Зафіксувати") },
    { _T("⏸ Hold"), _T("⏸ Зафіксувати") },
    { _T("▶ Live"), _T("▶ Наживо") },
    { _T("● Record"), _T("● Запис") },
    { _T("■ Stop rec"), _T("■ Зупинити запис") },
    { _T("Open..."), _T("Відкрити запис...") },
    { _T("Save frame"), _T("Зберегти кадр") },
    { _T("Clear"), _T("Очистити") },
    { _T("Replay"), _T("Відтворення") },
    { _T("Play"), _T("Грати") },
    { _T("Pause"), _T("Пауза") },
    { _T("Close"), _T("Закрити") },
    { _T("max"), _T("макс") },

    // Settings tab: MCU
    { _T("MCU acquisition"), _T("Захоплення на МК") },
    { _T("Mode"), _T("Режим роботи") },
    { _T("Idle"), _T("Очікування") },
    { _T("Continuous"), _T("Безперервний") },
    { _T("Single"), _T("Одиночний") },
    { _T("Apply"), _T("Застосувати") },
    { _T("Set"), _T("Задати") },
    { _T("Chirp freq, Hz (100..24000)"), _T("Частота повторення чірпів, Гц (100..24000)") },
    { _T("Samples (0 = auto)"), _T("Відліків АЦП за захоплення (0 = авто)") },
    { _T("Interval, ms"), _T("Пауза між захопленнями, мс") },
    { _T("Chirp amplitude, DAC"), _T("Амплітуда чірпа, коди DAC") },
    { _T("Chirp offset (base), DAC"), _T("Нижній рівень чірпа, коди DAC") },
    { _T("Chirps per capture"), _T("Чірпів за одне захоплення (burst)") },
    { _T("Ramp rise / fall, us"), _T("Тривалість підйому / спаду, мкс") },
    { _T("Set ramp"), _T("Задати рампу") },
    { _T("Frame content"), _T("Що передає кадр") },
    { _T("Raw"), _T("Відліки") },
    { _T("FFT"), _T("Спектр МК") },
    { _T("Ping"), _T("Ping") },
    { _T("Get status"), _T("Прочитати статус") },
    { _T("Send all"), _T("Надіслати все") },

    // Settings tab: radar / VCO
    { _T("Radar geometry"), _T("Параметри радара") },
    { _T("VCO (HMC431)"), _T("Генератор VCO (HMC431)") },
    { _T("f0 / B from tuning curve"), _T("f0 і B з кривої перестроювання") },
    { _T("Vtune at DAC 0 / 4095, V"), _T("Напруга Vtune при коді DAC 0 / 4095, В") },
    { _T("Tuning curve V:GHz,..."), _T("Крива VCO: В:ГГц, В:ГГц, ...") },
    { _T("Carrier f0 (sweep centre), GHz"), _T("Центральна частота f0, ГГц") },
    { _T("Sweep bandwidth B, MHz"), _T("Смуга перестроювання B, МГц") },
    { _T("Ramp time, ms (0 = auto)"), _T("Тривалість рампи, мс (0 = авто)") },
    { _T("Range offset, m"), _T("Поправка нуля дальності, м") },
    { _T("Modulation"), _T("Форма чірпа") },
    { _T("Chirps per frame"), _T("Чірпів у кадрі для обробки") },
    { _T("= burst"), _T("як burst") },
    { _T("UP/DOWN pair gate, m/s"), _T("Макс. швидкість для пари UP/DOWN, м/с") },

    // Settings tab: application
    { _T("Application"), _T("Програма") },
    { _T("Theme"), _T("Тема оформлення") },
    { _T("Dark"), _T("Темна") },
    { _T("Language"), _T("Мова інтерфейсу") },
    { _T("Fallback Fs, Hz"), _T("Частота АЦП, якщо кадр її не містить, Гц") },
    { _T("ADC clock corr., ppm"), _T("Поправка тактової частоти АЦП, ppm") },
    { _T("Log"), _T("Журнал зв'язку") },
    { _T("Per-frame RX lines"), _T("Записувати кожен прийнятий кадр") },
    { _T("Start-up"), _T("При запуску") },
    { _T("Auto-connect"), _T("Підключатися автоматично") },
    { _T("The language changes after the application is restarted."), _T("Мова інтерфейсу зміниться після перезапуску програми.") },

    // Derived values (grouped read-out)
    { _T("Derived values"), _T("Розраховані параметри") },
    { _T("VCO sweep"), _T("Перестроювання VCO") },
    { _T("DAC %d..%d = Vtune %.2f..%.2f V = %.4f..%.4f GHz"), _T("коди DAC %d..%d = Vtune %.2f..%.2f В = %.4f..%.4f ГГц") },
    { _T("B = %.1f MHz, slope %.0f..%.0f MHz/V, sweep nonlinearity %.1f%%"), _T("смуга B = %.1f МГц, крутизна %.0f..%.0f МГц/В, нелінійність %.1f%%") },
    { _T(" [Vtune outside the curve table!]"), _T(" [Vtune поза межами таблиці кривої!]") },
    { _T("tuning curve invalid (need >= 2 points V:GHz)"), _T("крива перестроювання некоректна (потрібно щонайменше 2 точки В:ГГц)") },
    { _T("Chirp"), _T("Чірп") },
    { _T("ramp %.4f ms, period %.4f ms"), _T("рампа %.4f мс, період %.4f мс") },
    { _T("%zu samples per ramp, %zu of them go into the FFT"), _T("%zu відліків на рампу, з них %zu ідуть у FFT") },
    { _T("Spectrum"), _T("Спектр") },
    { _T("decimation x%d: effective Fs %.1f kHz, FFT %zu points"), _T("проріджування x%d: ефективна Fs %.1f кГц, FFT на %zu точок") },
    { _T("one bin = %.1f Hz"), _T("один бін = %.1f Гц") },
    { _T(" = %.3f m"), _T(" = %.3f м") },
    { _T("Range"), _T("Дальність") },
    { _T("resolution c/2B = %.3f m (effective %.3f m)"), _T("роздільна здатність c/2B = %.3f м (фактична %.3f м)") },
    { _T("maximum %.1f m, beat frequency %.1f Hz per metre"), _T("максимум %.1f м, частота биття %.1f Гц на метр") },
    { _T("set bandwidth B > 0 for a range axis"), _T("задайте смугу B > 0, щоб була вісь дальності") },
    { _T("Velocity"), _T("Швидкість") },
    { _T("resolution %.3f m/s (burst %d), unambiguous +/- %.2f m/s"), _T("роздільна здатність %.3f м/с (burst %d), однозначно до +/- %.2f м/с") },
    { _T("USB link"), _T("Канал USB") },
    { _T("%.2f MB/s at %d ms interval (full-speed CDC limit ~0.8 MB/s)"), _T("%.2f МБ/с при паузі %d мс (межа USB full-speed CDC ~0.8 МБ/с)") },
    { _T("\r\n%sADC clock %+.3f ppm: %.6f -> %.6f MS/s"), _T("\r\n%sтакт АЦП %+.3f ppm: %.6f -> %.6f МВ/с") },

    // Processing panel
    { _T("Processing"), _T("Обробка сигналу") },
    { _T("Spectrum source"), _T("Джерело спектра") },
    { _T("RAW on PC"), _T("Обчислювати на ПК") },
    { _T("MCU FFT"), _T("Спектр з МК") },
    { _T("Ramp guard, % each end"), _T("Відкинути краї рампи, % з кожного боку") },
    { _T("Detrend"), _T("Нахил сигналу") },
    { _T("Remove linear trend"), _T("Прибирати лінійний нахил") },
    { _T("Decimation"), _T("Проріджування відліків") },
    { _T("Auto"), _T("Автоматично") },
    { _T("Range of interest, m"), _T("Робоча дальність (до), м") },
    { _T("Window"), _T("Вагове вікно FFT") },
    { _T("Kaiser beta"), _T("Параметр beta вікна Кайзера") },
    { _T("Zero padding"), _T("Доповнення FFT нулями") },
    { _T("Range gain"), _T("Компенсація загасання з дальністю") },
    { _T("Off"), _T("Вимкнено") },
    { _T("20 dB/dec (R^2)"), _T("20 дБ/декаду (R^2)") },
    { _T("40 dB/dec (R^4)"), _T("40 дБ/декаду (R^4)") },
    { _T("Chirp split"), _T("Поділ кадру на рампи") },
    { _T("From frame header"), _T("За даними прошивки в заголовку кадру") },
    { _T("Tone estimate"), _T("Точна частота тону") },
    { _T("Precise (double FFT)"), _T("Окремим FFT подвійної точності") },
    { _T("Rectangular"), _T("Прямокутне (без вікна)") },
    { _T("Hann"), _T("Ханна") },
    { _T("Hamming"), _T("Хеммінга") },
    { _T("Blackman"), _T("Блекмана") },
    { _T("Blackman-Harris 4"), _T("Блекмана-Харріса (4 члени)") },
    { _T("Kaiser"), _T("Кайзера") },
    { _T("Flat-top"), _T("Плоска вершина (точна амплітуда)") },
    { _T("Detection"), _T("Виявлення цілей") },
    { _T("Detector"), _T("Спосіб формування порога") },
    { _T("Noise floor + X dB"), _T("Рівень шуму + X дБ") },
    { _T("CA-CFAR"), _T("CA-CFAR: середнє сусідніх комірок") },
    { _T("OS-CFAR"), _T("OS-CFAR: порядкова статистика") },
    { _T("GO-CFAR (greatest of)"), _T("GO-CFAR: більше з двох боків") },
    { _T("SO-CFAR (smallest of)"), _T("SO-CFAR: менше з двох боків") },
    { _T("Threshold above noise, dB"), _T("Поріг над рівнем шуму, дБ") },
    { _T("CFAR false-alarm prob."), _T("Ймовірність хибної тривоги CFAR") },
    { _T("0.01  (1 in 100)"), _T("0.01  (1 на 100 комірок)") },
    { _T("0.001  (1 in 1000)"), _T("0.001  (1 на 1000)") },
    { _T("0.0001  (1 in 10 000)"), _T("0.0001  (1 на 10 000)") },
    { _T("0.00001  (1 in 100 000)"), _T("0.00001  (1 на 100 000)") },
    { _T("0.000001  (1 in 1 000 000)"), _T("0.000001  (1 на 1 000 000)") },
    { _T("CFAR guard cells"), _T("Захисні комірки CFAR біля піка") },
    { _T("CFAR training cells"), _T("Опорні комірки CFAR для оцінки шуму") },
    { _T("Peak interpolation"), _T("Уточнення частоти піка між бінами") },
    { _T("None"), _T("Без уточнення") },
    { _T("Parabolic (dB)"), _T("Парабола по дБ") },
    { _T("Jacobsen"), _T("Якобсена") },
    { _T("Candan"), _T("Кандана") },
    { _T("Quinn (2nd)"), _T("Квінна (2-й)") },
    { _T("Max targets"), _T("Макс. кількість цілей") },
    { _T("Doppler"), _T("Карта дальність-швидкість") },
    { _T("MTI (subtract mean)"), _T("Прибирати нерухомі відбиття (MTI)") },
    { _T("Tracking"), _T("Супровід цілей") },
    { _T("Stable target IDs"), _T("Зберігати номер цілі між кадрами") },
    { _T("Rejection"), _T("Фільтрація хибних піків") },
    { _T("Harmonics"), _T("Гармоніки") },
    { _T("Drop 2f, 3f.. of a stronger peak"), _T("Відкидати кратні частоти (2f, 3f...) сильного піка") },
    { _T("Harmonic weaker by, dB"), _T("Гармоніка слабша за основну щонайменше на, дБ") },
    { _T("Min SNR, dB (0 = off)"), _T("Мінімальне відношення сигнал/шум, дБ (0 = вимк.)") },
    { _T("Confirm after N frames"), _T("Показувати ціль після N кадрів поспіль") },
    { _T("Spur mask Hz:halfwidth,..."), _T("Ігнорувати частоти, Гц:півширина, ...") },
    { _T("Learn spurs"), _T("Запам'ятати поточні піки") },
    { _T("Display"), _T("Відображення") },
    { _T("dB axis top"), _T("Шкала дБ: верхня межа") },
    { _T("dB axis bottom"), _T("Шкала дБ: нижня межа") },
    { _T("Waterfall rows"), _T("Глибина водоспаду, кадрів") },
    { _T("ADC bits"), _T("Розрядність АЦП, біт") },
    { _T("ADC full scale, V"), _T("Опорна напруга АЦП, В") },
    { _T("Defaults"), _T("Скинути до типових") },

    // Radar tab
    { _T("Trace:"), _T("Накопичення:") },
    { _T("Clear write"), _T("Без накопичення") },
    { _T("Average"), _T("Усереднення") },
    { _T("Max hold"), _T("Утримання максимуму") },
    { _T("Min hold"), _T("Утримання мінімуму") },
    { _T("Palette:"), _T("Палітра:") },
    { _T("UP"), _T("UP") },
    { _T("DOWN"), _T("DOWN") },
    { _T("Threshold"), _T("Поріг") },
    { _T("Noise"), _T("Шум") },
    { _T("Range-Doppler"), _T("Дальність-швидкість") },
    { _T("Reset avg"), _T("Скинути накопичення") },
    { _T("Autoscale"), _T("Автомасштаб") },
    { _T("Clear WF"), _T("Очистити водоспад") },
    { _T("Phase @ %s: %+.3f mm"), _T("Фаза на %s: зміщення %+.3f мм") },
    { _T("Range profile"), _T("Спектр биття / профіль дальності") },
    { _T("Waterfall (range - time)"), _T("Водоспад (дальність - час)") },
    { _T("Range - Doppler"), _T("Дальність - швидкість") },
    { _T("no data"), _T("немає даних") },
    { _T("threshold"), _T("поріг") },
    { _T("noise"), _T("шум") },
    { _T("frame %u   t = %u ms   bin %.1f Hz"), _T("кадр %u   t = %u мс   бін %.1f Гц") },
    { _T("   fs/%d = %s   N = %zu   DSP %.1f ms"), _T("   fs/%d = %s   N = %zu   обробка %.1f мс") },
    { _T("   [MCU FFT]"), _T("   [спектр з МК]") },
    { _T("   rejected: %d harmonic, %d spur, %d low SNR, %d unconfirmed"), _T("   відкинуто: гармонік %d, завад %d, слабких %d, непідтверджених %d") },
    { _T("Reset zoom\tHome"), _T("Скинути масштаб\tHome") },
    { _T("Reset zoom"), _T("Скинути масштаб") },
    { _T("Autoscale dB\tA"), _T("Автомасштаб дБ\tA") },
    { _T("Autoscale colours"), _T("Автомасштаб кольорів") },
    { _T("Markers on two strongest peaks"), _T("Маркери на два найсильніші піки") },
    { _T("Clear markers\tEsc"), _T("Прибрати маркери\tEsc") },
    { _T("Clear cursors\tEsc"), _T("Прибрати курсори\tEsc") },
    { _T("Clear history"), _T("Очистити історію") },
    { _T("Copy image"), _T("Копіювати зображення") },
    { _T("needs chirps per frame > 1 (burst)"), _T("потрібно більше одного чірпа в кадрі (burst)") },
    { _T("%zu rows   palette %s"), _T("%zu рядків   палітра %s") },
    { _T("%d chirps   %d x %d   v bin %.3f m/s   v max %.2f m/s"), _T("%d чірпів   %d x %d   крок швидкості %.3f м/с   макс. %.2f м/с") },

    // Target / frame lists
    { _T("R, m"), _T("R, м") },
    { _T("v, m/s"), _T("v, м/с") },
    { _T("f_up, kHz"), _T("f_up, кГц") },
    { _T("f_dn, kHz"), _T("f_dn, кГц") },
    { _T("A, dBFS"), _T("A, дБFS") },
    { _T("SNR, dB"), _T("С/Ш, дБ") },
    { _T("pair"), _T("пара") },
    { _T("yes"), _T("так") },
    { _T("no"), _T("ні") },
    { _T("t, ms"), _T("t, мс") },

    // Scope tab
    { _T("Frame (all chirps)"), _T("Кадр (усі чірпи)") },
    { _T("Ramp detail"), _T("Окрема рампа") },
    { _T("Ramp:"), _T("Рампа:") },
    { _T("Dots"), _T("Точками") },
    { _T("Volts"), _T("Вольти") },
    { _T("ADC codes"), _T("Коди АЦП") },
    { _T("Frame %u  (%zu samples, %d chirps)"), _T("Кадр %u  (%zu відліків, %d чірпів)") },
    { _T("  UP %zu + DOWN %zu smp"), _T("  UP %zu + DOWN %zu відліків") },
    { _T(", %zu after the last chirp (unused)"), _T(", %zu після останнього чірпа (не обробляються)") },
    { _T("Ramp detail: %s #%d  (%zu samples in the ramp"), _T("Окрема рампа: %s #%d  (%zu відліків у рампі") },
    { _T(", %.1f beat cycles of %s"), _T(", %.1f періодів биття частотою %s") },
    { _T(", %.1f cycles of %s"), _T(", %.1f періодів частотою %s") },
    { _T(", +%zu guard"), _T(", +%zu відкинутих з країв") },
    { _T("guard %zu smp"), _T("край %zu відл.") },
    { _T("%s #%d: %zu smp, %s"), _T("%s #%d: %zu відл., %s") },
    { _T("   tone UP %.1f Hz"), _T("   точний тон UP %.1f Гц") },
    { _T(" / DOWN %.1f Hz"), _T(" / DOWN %.1f Гц") },
    { _T("   MCU peak %.1f Hz"), _T("   пік за даними МК %.1f Гц") },
    { _T("   decim x%d, fs_eff %s, ramp %s%s"), _T("   проріджування x%d, ефективна Fs %s, рампа %s%s") },
    { _T(" (hdr)"), _T(" (з заголовка)") },

    // Communication tab
    { _T("Time"), _T("Час") },
    { _T("Kind"), _T("Тип") },
    { _T("Message"), _T("Повідомлення") },
    { _T("All"), _T("Усі") },
    { _T("Errors"), _T("Помилки") },
    { _T("Service (ACK/STATUS/PONG)"), _T("Службові (ACK/STATUS/PONG)") },
    { _T("Port / info"), _T("Порт / інформація") },
    { _T("Auto-scroll"), _T("Автопрокрутка") },
    { _T("Copy"), _T("Копіювати") },
    { _T("Save..."), _T("Зберегти...") },
    { _T("Cannot write the log file."), _T("Не вдалося записати файл журналу.") },
    { _T("Text files (*.txt)|*.txt|All files (*.*)|*.*||"), _T("Текстові файли (*.txt)|*.txt|Усі файли (*.*)|*.*||") },

    // Trace tab
    { _T("Trace enabled (MCU test mode)"), _T("Трасування увімкнено (тестовий режим МК)") },
    { _T("Trace not compiled into firmware"), _T("Трасування не вбудоване у прошивку") },
    { _T("Single shot"), _T("Одне захоплення") },
    { _T("Get trace"), _T("Отримати трасу") },
    { _T("Export CSV..."), _T("Експорт у CSV...") },
    { _T("No trace received. Enable trace, then fire a single shot."), _T("Траса не отримана. Увімкніть трасування і зробіть одне захоплення.") },
    { _T("No trace to export."), _T("Немає траси для експорту.") },
    { _T("Cleared."), _T("Очищено.") },
    { _T("Cannot create file."), _T("Не вдалося створити файл.") },
    { _T("CSV files (*.csv)|*.csv|All files (*.*)|*.*||"), _T("Файли CSV (*.csv)|*.csv|Усі файли (*.*)|*.*||") },
    { _T("t, us"), _T("t, мкс") },
    { _T("dt, us"), _T("dt, мкс") },
    { _T("tick, ms"), _T("тік, мс") },
    { _T("ctx"), _T("контекст") },
    { _T("event"), _T("подія") },
    { _T("details"), _T("деталі") },
    { _T("%u records (%u dropped), span %u.%03u ms, capture tick %u ms, chirp %u Hz, amp %u, burst %u, rise/fall %u/%u us"),
      _T("%u записів (%u втрачено), тривалість %u.%03u мс, тік захоплення %u мс, чірп %u Гц, амплітуда %u, burst %u, підйом/спад %u/%u мкс") },

    // Main frame / status bar / dialogs
    { _T("Disconnected"), _T("Не підключено") },
    { _T("Connected %s  %s%s"), _T("Підключено %s  %s%s") },
    { _T("RUNNING"), _T("ЗАХОПЛЕННЯ") },
    { _T("idle"), _T("очікування") },
    { _T("  [HOLD]"), _T("  [ЗАФІКСОВАНО]") },
    { _T("  ● REC"), _T("  ● ЗАПИС") },
    { _T("Replay %s  (%zu / %zu)"), _T("Відтворення %s  (%zu / %zu)") },
    { _T("MCU: -"), _T("МК: -") },
    { _T("Fs %.4f MS/s  %zu smp  %.1f fps  %.2f MB/s  RTT %lu ms"), _T("Fs %.4f МВ/с  %zu відл.  %.1f кадр/с  %.2f МБ/с  RTT %lu мс") },
    { _T("lost %llu  CRC %llu  hdr %llu"), _T("втрачено %llu  CRC %llu  заголовків %llu") },
    { _T("DSP %.1f ms"), _T("обробка %.1f мс") },
    { _T("buf %zu/%zu  %.0f MB"), _T("буфер %zu/%zu  %.0f МБ") },
    { _T("MCU rejected command 0x%02X: %s"), _T("МК відхилив команду 0x%02X: %s") },
    { _T("Select a COM port first."), _T("Спочатку виберіть COM-порт.") },
    { _T("Failed to open %s"), _T("Не вдалося відкрити %s") },
    { _T("No frame to save."), _T("Немає кадру для збереження.") },
    { _T("No frames in the buffer."), _T("У буфері немає кадрів.") },
    { _T("No raw samples in the current frame."), _T("У поточному кадрі немає відліків АЦП.") },
    { _T("Save failed."), _T("Збереження не вдалося.") },
    { _T("WAV export failed."), _T("Експорт WAV не вдався.") },
    { _T("Screenshot failed."), _T("Знімок екрана не вдався.") },
    { _T("Close the replay before recording."), _T("Закрийте відтворення перед записом.") },
    { _T("Cannot create the session file."), _T("Не вдалося створити файл сесії.") },
    { _T("Cannot open the session file."), _T("Не вдалося відкрити файл сесії.") },
    { _T("Recording started: "), _T("Запис розпочато: ") },
    { _T("Recording stopped: %llu frames"), _T("Запис зупинено: %llu кадрів") },
    { _T("Recording: write failed, stopping"), _T("Запис: помилка запису, зупинено") },
    { _T("REC %s  %llu frames  %.1f MB"), _T("ЗАПИС %s  %llu кадрів  %.1f МБ") },
    { _T("Replay opened: %s (%zu frames, Fs %u Hz)"), _T("Відтворення відкрито: %s (%zu кадрів, Fs %u Гц)") },
    { _T("FastAcq sessions (*.facq)|*.facq|All files (*.*)|*.*||"), _T("Сесії FastAcq (*.facq)|*.facq|Усі файли (*.*)|*.*||") },
    { _T("WAV files (*.wav)|*.wav|All files (*.*)|*.*||"), _T("Файли WAV (*.wav)|*.wav|Усі файли (*.*)|*.*||") },
    { _T("PNG images (*.png)|*.png||"), _T("Зображення PNG (*.png)|*.png||") },
    { _T("TRACE %u records, %u dropped (see Trace tab)"), _T("ТРАСА: %u записів, %u втрачено (див. вкладку Трасування МК)") },
    { _T("FastAcq 2.0\n\nFMCW radar IF-signal analyzer for the STM32H7 Fast Acquisition Device.\n"),
      _T("FastAcq 2.0\n\nАналізатор сигналу биття FMCW-радара для пристрою STM32H7 Fast Acquisition.\n") },
    { _T("C++17 / MFC / GDI, no third-party dependencies.\n\nMIT License."), _T("C++17 / MFC / GDI, без сторонніх бібліотек.\n\nЛіцензія MIT.") },
    { _T("Space\tStart / Stop acquisition\n"), _T("Пробіл\tСтарт / Стоп захоплення\n") },
    { _T("T\tTrigger a single capture\n"), _T("T\tОдиночне захоплення\n") },
    { _T("H\tHold / Live display\n"), _T("H\tЗафіксувати / Наживо\n") },
    { _T("R\tStart / stop recording\n"), _T("R\tПочати / зупинити запис\n") },
    { _T("F5\tConnect / disconnect\n"), _T("F5\tПідключити / відключити\n") },
    { _T("Ctrl+O\tOpen replay\n"), _T("Ctrl+O\tВідкрити запис\n") },
    { _T("Ctrl+S\tSave frame as CSV\n"), _T("Ctrl+S\tЗберегти кадр як CSV\n") },
    { _T("F12\tSave screenshot (PNG)\n"), _T("F12\tЗнімок екрана (PNG)\n") },
    { _T("Ctrl+1..5\tSwitch tab\n"), _T("Ctrl+1..5\tПеремкнути вкладку\n") },
    { _T("PgUp / PgDn, Ctrl+Left / Right\tPrevious / next frame\n\n"), _T("PgUp / PgDn, Ctrl+Вліво / Вправо\tПопередній / наступний кадр\n\n") },
    { _T("In plots: wheel = zoom at cursor, Shift+wheel = pan, drag = pan, double-click = reset,\n"),
      _T("На графіках: колесо = масштаб у точці курсора, Shift+колесо = зсув, перетягування = зсув, подвійний клік = скинути,\n") },
    { _T("click = marker A, Shift+click = marker B, Esc = clear markers, Home = reset zoom, A = autoscale dB."),
      _T("клік = маркер A, Shift+клік = маркер B, Esc = прибрати маркери, Home = скинути масштаб, A = автомасштаб дБ.") },

    // Chirp preview
    { _T("Chirp preview (what the MCU will generate)"), _T("Попередній перегляд чірпа (що згенерує МК)") },
    { _T("Parameters out of range: frequency 100..24000 Hz, period 41.7 us .. 10 ms."), _T("Параметри поза межами: частота 100..24000 Гц, період 41.7 мкс .. 10 мс.") },
    { _T("DAC code"), _T("Код DAC") },
    { _T("Vtune  /  VCO out"), _T("Vtune  /  частота VCO") },
    { _T("Vtune"), _T("Vtune") },
    { _T("next cycle"), _T("наступний цикл") },
    { _T("rise "), _T("підйом ") },
    { _T("fall "), _T("спад ") },
    { _T("burst x%u%s"), _T("burst x%u%s") },
    { _T(" (first 4 drawn)"), _T(" (намальовано перші 4)") },
    { _T("interval %u ms"), _T("пауза %u мс") },
    { _T("wait TRIGGER"), _T("очікує команди") },
    { _T("IDLE: trigger only"), _T("очікування: лише за командою") },
    { _T("T = %s   f = %.3f Hz   (%s)"), _T("T = %s   f = %.3f Гц   (%s)") },
    { _T("ramp mode: rise/fall"), _T("задано підйом/спад") },
    { _T("freq mode: symmetric"), _T("задано частоту, симетричний") },
    { _T("ADC @ %.0f MS/s: chirp = rise %u + fall %u = %u samples (%s)"), _T("АЦП %.0f МВ/с: чірп = підйом %u + спад %u = %u відліків (%s)") },
    { _T(";  burst x%u = %llu samples (%s)"), _T(";  burst x%u = %llu відліків (%s)") },
    { _T("OK: fits in ONE capture window of %u samples (%s, %u DMA chunks x %u) = %.1f chirps; MCU buffer %u samples (%s), %.0f%% used"),
      _T("OK: вміщається в ОДНЕ вікно захоплення %u відліків (%s, %u блоків DMA по %u) = %.1f чірпа; буфер МК %u відліків (%s), зайнято %.0f%%") },
    { _T("DOES NOT FIT: samples override %u cuts the burst to %u samples (%s) = %.2f chirps of %u; set samples to 0 (auto) or >= %llu"),
      _T("НЕ ВМІЩАЄТЬСЯ: задана кількість відліків %u обрізає burst до %u відліків (%s) = %.2f чірпа з %u; поставте 0 (авто) або >= %llu") },
    { _T("DOES NOT FIT: burst needs %llu samples (%s), MCU capture holds %u (%s) = %.2f chirps of %u; reduce burst or shorten the chirp"),
      _T("НЕ ВМІЩАЄТЬСЯ: burst потребує %llu відліків (%s), захоплення МК вміщає %u (%s) = %.2f чірпа з %u; зменшіть burst або вкоротіть чірп") },
    { _T("DAC %.0f..%.0f (offset %u + A %u): Vtune %.2f..%.2f V = %.3f..%.3f GHz (B %.0f MHz)"),
      _T("DAC %.0f..%.0f (нижній рівень %u + амплітуда %u): Vtune %.2f..%.2f В = %.3f..%.3f ГГц (B %.0f МГц)") },
    { _T("DAC %.0f..%.0f (offset %u + A %u): Vtune %.2f..%.2f V"), _T("DAC %.0f..%.0f (нижній рівень %u + амплітуда %u): Vtune %.2f..%.2f В") },
};

// ---------------------------------------------------------------------------
// Tooltips for input controls: what the field is, what it changes, how to
// choose it and the default. Terms are explained in plain words.
// ---------------------------------------------------------------------------
struct HelpEntry { UINT id; LPCTSTR en; LPCTSTR uk; };

const HelpEntry kHelp[] = {
    // Command panel
    { IDC_CMB_COM, _T("Serial (USB CDC) port of the FastAcq device. Refreshed when devices are plugged in; FastAcq ports come first."),
      _T("Послідовний порт (USB CDC) пристрою FastAcq. Список оновлюється при підключенні пристроїв; порти FastAcq ідуть першими.") },
    { IDC_BTN_CONNECT, _T("Open / close the selected port. After connecting the device status is read (GET_STATUS) and mirrored into the Settings tab."),
      _T("Відкрити / закрити вибраний порт. Після підключення програма читає статус пристрою (GET_STATUS) і показує його налаштування на вкладці Налаштування.") },
    { IDC_BTN_START, _T("Start continuous acquisition: the MCU captures a frame every 'Interval' ms."),
      _T("Почати безперервне захоплення: МК захоплює кадр через кожну задану паузу.") },
    { IDC_BTN_STOP, _T("Stop acquisition. Captured frames stay in the buffer."),
      _T("Зупинити захоплення. Захоплені кадри лишаються в буфері.") },
    { IDC_BTN_TRIGGER, _T("Capture one frame now. Works in Idle and Single modes."),
      _T("Захопити один кадр зараз. Працює в режимах Очікування та Одиночний.") },
    { IDC_BTN_ABORT, _T("Abort the capture in progress immediately."), _T("Негайно перервати поточне захоплення.") },
    { IDC_BTN_HOLD, _T("Hold freezes the display on the current frame (new frames are still buffered and recorded); Live follows the stream again. Key: H."),
      _T("Зафіксувати: екран зупиняється на поточному кадрі (нові кадри далі потрапляють у буфер і запис). Наживо: екран знову слідує за потоком. Клавіша H.") },
    { IDC_BTN_RECORD, _T("Start / stop recording every received frame into a .facq session file for later replay. Key: R."),
      _T("Почати / зупинити запис усіх прийнятих кадрів у файл сесії .facq, який потім можна відтворити без обладнання. Клавіша R.") },
    { IDC_BTN_OPEN_REPLAY, _T("Open a recorded .facq session and replay it through the same processing chain, without hardware."),
      _T("Відкрити записану сесію .facq і прогнати її через той самий ланцюг обробки, без підключеного пристрою.") },
    { IDC_BTN_SAVE_FRAME, _T("Save the current frame (raw samples and the MCU spectrum if present) as CSV. Key: Ctrl+S."),
      _T("Зберегти поточний кадр (відліки АЦП і спектр з МК, якщо він є) у CSV. Клавіша Ctrl+S.") },
    { IDC_BTN_CLEAR, _T("Clear the frame buffer, the waterfall history and the averages."),
      _T("Очистити буфер кадрів, історію водоспаду та накопичені спектри.") },
    { IDC_CMB_RP_SPEED, _T("Replay speed relative to the recorded timing; 'max' plays as fast as the processing allows."),
      _T("Швидкість відтворення відносно записаного часу; 'макс' грає так швидко, як встигає обробка.") },
    { IDC_SLD_RP_POS, _T("Position in the replayed session; drag to seek."), _T("Позиція у відтворюваній сесії; перетягніть, щоб перейти.") },

    // Settings: MCU acquisition
    { IDC_CMB_MODE, _T("MCU operating mode. Idle: nothing is captured until a trigger. Continuous: a frame every 'Interval' ms (default). Single: one frame per trigger, then back to waiting."),
      _T("Режим роботи МК. Очікування: нічого не захоплюється, доки не прийде команда. Безперервний: кадр через кожну паузу (типово). Одиночний: один кадр на команду, далі знову очікування.") },
    { IDC_EDT_FREQ, _T("Chirp repetition frequency, Hz (100..24000): one triangle (rise + fall) per period. The firmware quantizes it to timer ticks; the preview shows the actual value. Typing here leaves the explicit rise/fall mode. Default 458 Hz."),
      _T("Скільки чірпів (трикутників підйом + спад) за секунду генерує МК, Гц (100..24000). Прошивка округлює до тактів таймера; фактичне значення видно у попередньому перегляді. Введення тут вимикає режим явного підйому/спаду. Типово 458 Гц.") },
    { IDC_EDT_SAMPLES, _T("Capture length override in ADC samples (0 = automatic: one burst of chirps rounded up to a 16384-sample DMA block, max 650000). Set it only when a fixed length is needed; the preview turns red if it cuts the burst."),
      _T("Примусова довжина захоплення у відліках АЦП. 0 = автоматично: один burst чірпів, округлений угору до блоку DMA 16384 відліків, максимум 650000. Задавайте лише коли потрібна фіксована довжина; якщо вона обрізає burst, перегляд стає червоним.") },
    { IDC_EDT_INTERVAL, _T("Pause between capture cycles in Continuous mode, ms (5..10000; the firmware minimum is 5). Shorter = more frames per second and more USB traffic (see the derived values). Default 30 ms."),
      _T("Пауза між захопленнями у безперервному режимі, мс (5..10000; мінімум прошивки 5). Коротша пауза = більше кадрів за секунду і більше трафіку USB (див. розраховані параметри). Типово 30 мс.") },
    { IDC_EDT_AMPLITUDE, _T("Height of the chirp triangle in DAC codes (1..4095). With the base level it defines the tuning-voltage window of the VCO and therefore the swept band B. Default 4095."),
      _T("Висота трикутника чірпа у кодах DAC (1..4095). Разом із нижнім рівнем визначає діапазон напруги перестроювання VCO, а отже і смугу B. Типово 4095.") },
    { IDC_EDT_OFFSET, _T("Base level of the chirp in DAC codes (0..4094): the triangle runs from this level to level + amplitude, so the tuning voltage starts above 0 V. Needs firmware with CMD_SET_OFFSET. Default 0."),
      _T("Нижній рівень чірпа у кодах DAC (0..4094): трикутник іде від цього рівня до рівня + амплітуда, тобто напруга перестроювання починається не з 0 В. Потребує прошивки з командою CMD_SET_OFFSET. Типово 0.") },
    { IDC_EDT_BURST, _T("Chirps captured back-to-back in one frame (1..1024). More than one enables the range-velocity map and velocity resolution; the whole burst must fit the MCU buffer (see the preview). Default 1."),
      _T("Скільки чірпів підряд записується в один кадр (1..1024). Більше одного дає карту дальність-швидкість і роздільну здатність по швидкості; весь burst має вміститися в буфер МК (див. перегляд). Типово 1.") },
    { IDC_EDT_RISE, _T("Rise time of the chirp ramp, microseconds. With fall > 0 the explicit ramp mode (CMD_SET_RAMP) is used and asymmetric triangles are possible; the frequency field shows the result. 0/0 = symmetric from the frequency."),
      _T("Тривалість підйому рампи, мкс. Разом зі спадом > 0 вмикає режим явної рампи (CMD_SET_RAMP), можливий несиметричний трикутник; поле частоти показує результат. 0/0 = симетричний чірп із частоти.") },
    { IDC_EDT_FALL, _T("Fall time of the chirp ramp, microseconds (see rise). The DOWN ramp may be shorter than the UP ramp; the processing pairs them with k = T_fall / T_rise."),
      _T("Тривалість спаду рампи, мкс (див. підйом). Рампа DOWN може бути коротшою за UP; обробка враховує це при спарюванні (k = T_fall / T_rise).") },
    { IDC_CHK_RAW, _T("Send the raw ADC samples in every frame (needed for processing on the PC). Default on."),
      _T("Передавати відліки АЦП у кожному кадрі (потрібно для обробки на ПК). Типово увімкнено.") },
    { IDC_CHK_FFT, _T("Send the magnitude spectrum computed on the MCU. Needed only for the 'Spectrum from MCU' source; otherwise it just costs USB bandwidth. Default on."),
      _T("Передавати спектр амплітуд, обчислений на МК. Потрібно лише для джерела 'Спектр з МК', інакше просто забирає смугу USB. Типово увімкнено.") },
    { IDC_BTN_PING, _T("Send PING and measure the round-trip time to the device."), _T("Надіслати PING і виміряти час відповіді пристрою.") },
    { IDC_BTN_GET_STATUS, _T("Read the device configuration (mode, frequency, ramp, amplitude, burst, interval, trace) and mirror it into these fields."),
      _T("Прочитати налаштування пристрою (режим, частота, рампа, амплітуда, burst, пауза, трасування) і показати їх у цих полях.") },
    { IDC_BTN_SEND_ALL, _T("Send every MCU setting on this tab to the device in one go, then read the status back."),
      _T("Надіслати пристрою всі налаштування МК з цієї вкладки разом, потім прочитати статус.") },
    { IDC_BTN_SET_RAMP, _T("Send the rise / fall times (CMD_SET_RAMP). With both 0 the symmetric chirp from the frequency is sent instead."),
      _T("Надіслати тривалості підйому / спаду (CMD_SET_RAMP). Якщо обидві 0, замість цього надсилається симетричний чірп із частоти.") },

    // Settings: radar geometry / VCO
    { IDC_CHK_VCO, _T("Derive the centre frequency f0 and the swept band B from the VCO tuning curve and the chirp DAC window (base level .. base + amplitude) instead of typing them. Default on."),
      _T("Обчислювати центральну частоту f0 і смугу B з кривої перестроювання VCO та діапазону кодів DAC чірпа (нижній рівень .. рівень + амплітуда) замість ручного вводу. Типово увімкнено.") },
    { IDC_EDT_VTUNE_LO, _T("Tuning voltage the VCO receives at DAC code 0 (after the driver amplifier), volts. Default 0 V."),
      _T("Напруга перестроювання, яку VCO отримує при коді DAC 0 (після підсилювача), вольти. Типово 0 В.") },
    { IDC_EDT_VTUNE_HI, _T("Tuning voltage at DAC code 4095, volts. HMC431 tunes over 0..10 V. Default 10 V."),
      _T("Напруга перестроювання при коді DAC 4095, вольти. HMC431 перестроюється в межах 0..10 В. Типово 10 В.") },
    { IDC_EDT_VCO_CURVE, _T("VCO tuning curve as 'Vtune:GHz' points separated by commas, e.g. 0:5.50,1:5.59,...,10:6.10 (HMC431 typical). Linear interpolation between points; replace with values from the datasheet plot or a measurement."),
      _T("Крива перестроювання VCO як точки 'В:ГГц' через кому, напр. 0:5.50,1:5.59,...,10:6.10 (типова HMC431). Між точками лінійна інтерполяція; замініть значеннями з графіка даташиту або вимірювання.") },
    { IDC_EDT_F0, _T("Centre frequency of the sweep, GHz. Sets the wavelength used for velocity (v = lambda * fd / 2) and phase. Read-only while derived from the VCO curve."),
      _T("Центральна частота свіпу, ГГц. Задає довжину хвилі, з якої рахуються швидкість (v = lambda * fd / 2) і фаза. Лише читання, поки обчислюється з кривої VCO.") },
    { IDC_EDT_BW, _T("Swept bandwidth B, MHz. Range = c * T_ramp * f_beat / (2 B); range resolution = c / (2 B). Read-only while derived from the VCO curve."),
      _T("Смуга перестроювання B, МГц. Дальність = c * T_рампи * f_биття / (2 B); роздільна здатність по дальності = c / (2 B). Лише читання, поки обчислюється з кривої VCO.") },
    { IDC_EDT_TRAMP, _T("Ramp duration override, ms. 0 = automatic from the chirp frequency / frame header (recommended)."),
      _T("Примусова тривалість рампи, мс. 0 = автоматично з частоти чірпа або заголовка кадру (рекомендовано).") },
    { IDC_EDT_ROFFSET, _T("Zero-range calibration, m: subtracted from every range (cable and antenna delay). Put a reflector at a known distance and adjust until it reads right. Default 0."),
      _T("Поправка нуля дальності, м: віднімається від кожної дальності (затримка в кабелях і антені). Поставте відбивач на відомій відстані й підберіть значення. Типово 0.") },
    { IDC_CMB_SHAPE, _T("Chirp shape in the data. Triangle: each chirp = UP + DOWN ramp (range and velocity from the pair). Sawtooth: UP only. Single ramp: the whole frame is one ramp."),
      _T("Форма чірпа у даних. Трикутник: кожен чірп = рампа UP + DOWN (дальність і швидкість з пари). Пилка: лише UP. Одна рампа: весь кадр одна рампа.") },
    { IDC_CHK_CHIRPS_AUTO, _T("Take the number of chirps per frame from the device burst setting (recommended)."),
      _T("Брати кількість чірпів у кадрі з налаштування burst пристрою (рекомендовано).") },
    { IDC_EDT_CHIRPS, _T("Chirps per frame used by the processing when not taken from the burst setting."),
      _T("Кількість чірпів у кадрі для обробки, коли вона не береться з burst.") },
    { IDC_EDT_PAIR_V, _T("Largest velocity for which an UP peak and a DOWN peak are still paired as one target, m/s. Larger values pair more aggressively (risk of ghost targets). Default 30."),
      _T("Найбільша швидкість, при якій пік UP і пік DOWN ще вважаються однією ціллю, м/с. Більше значення спарює агресивніше (ризик хибних цілей). Типово 30.") },

    // Settings: application
    { IDC_CHK_DARK, _T("Dark colour theme for every view."), _T("Темна тема оформлення для всіх вікон.") },
    { IDC_CMB_LANG, _T("User-interface language. Applied after the application is restarted."), _T("Мова інтерфейсу. Застосовується після перезапуску програми.") },
    { IDC_EDT_FSCAL, _T("Sample rate used when a frame carries none, Hz. Normally the device reports 60 000 000 and this value is not used. Default 60058600."),
      _T("Частота дискретизації, яка використовується, якщо кадр її не містить, Гц. Зазвичай пристрій повідомляє 60 000 000 і це значення не потрібне. Типово 60058600.") },
    { IDC_EDT_PPM, _T("Correction of the ADC clock in ppm (parts per million), applied to the sample rate the device reports; all frequencies, ranges and the WAV export follow. Measure a known test tone and set ppm = (f_true / f_measured - 1) * 1e6. Default 0."),
      _T("Поправка тактової частоти АЦП у ppm (мільйонних частках), застосовується до частоти, яку повідомляє пристрій; за нею перераховуються всі частоти, дальності та експорт WAV. Виміряйте відомий тестовий тон і задайте ppm = (f_істинна / f_виміряна - 1) * 1e6. Типово 0.") },
    { IDC_BTN_APPLY_PPM, _T("Apply the ppm correction now (also applied when the field loses focus)."), _T("Застосувати поправку ppm зараз (також застосовується, коли поле втрачає фокус).") },
    { IDC_CHK_VERBOSE, _T("Write a log line for every received frame (useful when debugging the link, noisy otherwise)."),
      _T("Писати рядок журналу про кожен прийнятий кадр (корисно при налагодженні зв'язку, інакше засмічує журнал).") },
    { IDC_CHK_AUTOCONNECT, _T("Connect to the first FastAcq port automatically at start-up."), _T("Автоматично підключатися до першого порту FastAcq під час запуску.") },

    // Processing panel
    { IDC_RDO_SRC_RAW, _T("Compute the spectrum on the PC from the raw samples (full processing chain, recommended)."),
      _T("Обчислювати спектр на ПК з відліків АЦП (повний ланцюг обробки, рекомендовано).") },
    { IDC_RDO_SRC_MCU, _T("Use the magnitude spectrum computed on the MCU (needs 'Spectrum MCU' in the frame content). No UP/DOWN pairing, no range-velocity map."),
      _T("Використовувати спектр, обчислений на МК (потрібно увімкнути 'Спектр МК' у вмісті кадру). Без спарювання UP/DOWN і карти дальність-швидкість.") },
    { IDC_EDT_GUARD, _T("Percentage of each ramp dropped at both ends before the FFT (0..45). The VCO reverses its sweep at the turnaround and the beat is transient there; 0 uses every sample. Default 5 %."),
      _T("Скільки відсотків кожної рампи відкидається з обох кінців перед FFT (0..45). На зламі трикутника VCO змінює напрям перестроювання, і частота биття там ще не встановилася; 0 = використовувати всі відліки. Типово 5 %.") },
    { IDC_CHK_DETREND, _T("Remove a linear trend (slope) from every ramp; the mean is always removed. Suppresses leakage of the DC component into the first bins. Default on."),
      _T("Прибирати лінійний нахил сигналу в кожній рампі (середнє значення віднімається завжди). Зменшує протікання постійної складової у перші біни спектра. Типово увімкнено.") },
    { IDC_CMB_DECIM, _T("Decimation = keeping every N-th sample after a low-pass filter. It lowers the processed sample rate (fewer computations) and limits the spectrum to fs/(2N). Auto picks the largest N that still covers the working range plus 25 %; a fixed factor overrides it. Resolution is not affected."),
      _T("Проріджування (децимація) = після фільтра нижніх частот лишається кожен N-й відлік. Зменшує обсяг обчислень і обмежує спектр частотою fs/(2N). Автоматично береться найбільше N, при якому ще покривається робоча дальність із запасом 25 %; фіксоване значення перекриває авто. На роздільну здатність не впливає.") },
    { IDC_EDT_MAXRANGE, _T("Working range, m: the farthest distance the spectrum has to cover. Drives the automatic decimation and the default plot span. Zooming out with the wheel on the Radar tab raises it automatically."),
      _T("Робоча дальність, м: до якої відстані має сягати спектр. Від неї залежать автоматичне проріджування і початковий масштаб графіків. Відкручування колеса миші на вкладці Радар збільшує її автоматично.") },
    { IDC_CMB_WINDOW, _T("Weighting window applied to each ramp before the FFT; it trades peak width against sidelobe level. Hann: good general choice. Hamming: narrower peak. Blackman / Blackman-Harris: lowest sidelobes (weak targets next to strong ones). Kaiser: adjustable with beta. Flat-top: exact amplitudes, wide peaks."),
      _T("Вагове вікно, яким множиться рампа перед FFT; компроміс між шириною піка і рівнем бічних пелюсток. Ханна: хороший загальний вибір. Хеммінга: вужчий пік. Блекмана / Блекмана-Харріса: найнижчі бічні пелюстки (слабкі цілі поруч із сильними). Кайзера: регулюється параметром beta. Плоска вершина: точна амплітуда, широкий пік.") },
    { IDC_EDT_KAISER, _T("Shape parameter of the Kaiser window only: larger beta = lower sidelobes but a wider peak. 9 gives about -70 dB sidelobes."),
      _T("Параметр форми лише для вікна Кайзера: більше beta = нижчі бічні пелюстки, але ширший пік. 9 дає близько -70 дБ.") },
    { IDC_CMB_ZEROPAD, _T("Zero padding appends zeros to the ramp before the FFT (x1..x8): more points per bin, a smoother plot and finer peak interpolation. It does not improve the true resolution. Default x2."),
      _T("Доповнення нулями: до рампи перед FFT додаються нулі (x1..x8). Дає більше точок на бін, гладший графік і точніше уточнення частоти піка. Справжню роздільну здатність не покращує. Типово x2.") },
    { IDC_CMB_RANGEGAIN, _T("Tilt added to the spectrum to compensate how echo power falls with range: 20 dB/decade (R^2, point-like) or 40 dB/decade (R^4, radar equation). Off shows raw levels."),
      _T("Нахил, що додається до спектра, щоб компенсувати спадання потужності луни з дальністю: 20 дБ/декаду (R^2) або 40 дБ/декаду (R^4, рівняння радара). Вимкнено = сирі рівні.") },
    { IDC_CHK_FW_GEOM, _T("Split the frame into chirps and UP/DOWN ramps using the geometry the firmware writes into the frame header (exact sample counts in protocol v2). Off: frame length / chirps / 2. Default on."),
      _T("Ділити кадр на чірпи та рампи UP/DOWN за геометрією, яку прошивка записує в заголовок кадру (точні кількості відліків у протоколі v2). Вимкнено: довжина кадру / чірпи / 2. Типово увімкнено.") },
    { IDC_CHK_TONE, _T("Additionally estimate the strongest tone of each ramp with a separate double-precision FFT (Hann ratio interpolation, about 0.5 Hz accuracy); shown on the Scope tab."),
      _T("Додатково визначати найсильніший тон кожної рампи окремим FFT подвійної точності (інтерполяція за сусідніми бінами вікна Ханна, точність близько 0.5 Гц); показується на вкладці Осцилограф.") },
    { IDC_CMB_DETECTOR, _T("How the detection threshold is formed. Noise floor + X dB: fixed margin above the median noise. CFAR (constant false-alarm rate) adapts the threshold to the local noise around each bin: CA = mean of the neighbouring cells; OS = ordered statistic, robust to nearby targets; GO = greater of the two sides, fewer false alarms at clutter edges; SO = smaller of the two sides, keeps targets next to clutter edges."),
      _T("Як формується поріг виявлення. Рівень шуму + X дБ: фіксований запас над медіаною шуму. CFAR (стала ймовірність хибної тривоги) підлаштовує поріг під шум навколо кожного біна: CA = середнє сусідніх комірок; OS = порядкова статистика, стійка до сусідніх цілей; GO = більше з двох боків, менше хибних тривог на краю завад; SO = менше з двох боків, зберігає ціль поруч із завадою.") },
    { IDC_EDT_THRESH, _T("Margin above the noise estimate for the 'Noise floor + X dB' detector, dB. Default 12."),
      _T("Запас над оцінкою шуму для порога 'Рівень шуму + X дБ', дБ. Типово 12.") },
    { IDC_CMB_PFA, _T("Probability that a bin with noise only is reported as a target by the CFAR detectors. Smaller = higher threshold, fewer false alarms, weaker targets lost. Default 0.0001."),
      _T("Ймовірність того, що бін, у якому є лише шум, детектор CFAR визнає ціллю. Менше = вищий поріг, менше хибних тривог, але слабкі цілі губляться. Типово 0.0001.") },
    { IDC_EDT_CFAR_GUARD, _T("Bins right next to the tested bin that are excluded from the noise estimate, so the target's own energy does not raise the threshold. About the peak width in bins. Default 2."),
      _T("Біни впритул до перевірюваного, які не входять в оцінку шуму, щоб енергія самої цілі не піднімала поріг. Приблизно ширина піка в бінах. Типово 2.") },
    { IDC_EDT_CFAR_TRAIN, _T("Bins on each side used to estimate the noise. More = steadier threshold but slower to follow a changing noise floor. Default 16."),
      _T("Біни з кожного боку, за якими оцінюється шум. Більше = стабільніший поріг, але повільніше реагує на зміну шуму. Типово 16.") },
    { IDC_CMB_INTERP, _T("Estimates the peak frequency between FFT bins. Parabola on dB: works with every window. Jacobsen / Candan / Quinn: use the complex bins, most accurate with a rectangular window."),
      _T("Уточнює частоту піка між бінами FFT. Парабола по дБ: працює з будь-яким вікном. Якобсена / Кандана / Квінна: використовують комплексні біни, найточніші з прямокутним вікном.") },
    { IDC_EDT_MAXPEAKS, _T("Maximum number of targets reported per frame (strongest first), 1..64. Default 10."),
      _T("Максимальна кількість цілей на кадр (спочатку найсильніші), 1..64. Типово 10.") },
    { IDC_CHK_MTI, _T("Range-velocity map: subtract the mean over the chirps of the burst, so static reflections (clutter) disappear and only moving targets remain. Default on."),
      _T("Карта дальність-швидкість: відняти середнє по чірпах burst, щоб нерухомі відбиття зникли і лишилися лише рухомі цілі. Типово увімкнено.") },
    { IDC_CHK_TRACK, _T("Match targets between frames by range so a target keeps the same number (needed for 'show after N frames'). Default on."),
      _T("Зіставляти цілі між кадрами за дальністю, щоб ціль зберігала той самий номер (потрібно для 'показувати після N кадрів'). Типово увімкнено.") },
    { IDC_CHK_HARMONICS, _T("Drop peaks sitting at 2, 3 ... 5 times the frequency of a stronger peak and weaker by at least the dB below: mixer and ADC nonlinearity create such copies of a strong beat tone. Default off."),
      _T("Відкидати піки на частотах у 2, 3 ... 5 разів вищих за частоту сильнішого піка, якщо вони слабші щонайменше на вказані дБ: такі копії сильного тону створює нелінійність змішувача та АЦП. Типово вимкнено.") },
    { IDC_EDT_HARM_DROP, _T("A candidate harmonic must be at least this much weaker than its fundamental to be dropped, dB. Default 6."),
      _T("Пік вважається гармонікою і відкидається, лише якщо він слабший за основний тон щонайменше на стільки дБ. Типово 6.") },
    { IDC_EDT_MIN_SNR, _T("Peaks whose signal-to-noise ratio is below this value are not reported, dB. 0 = off."),
      _T("Піки, у яких відношення сигнал/шум нижче цього значення, не показуються, дБ. 0 = вимкнено.") },
    { IDC_EDT_CONFIRM, _T("A target is listed only after it has been seen in this many consecutive frames (0 or 1 = immediately). Removes single-frame false alarms at the cost of a short delay."),
      _T("Ціль показується лише після того, як її бачили стільки кадрів поспіль (0 або 1 = одразу). Прибирає хибні тривоги, що тривають один кадр, ціною невеликої затримки.") },
    { IDC_EDT_SPURS, _T("Frequency bands to ignore, as 'centre:halfwidth' in Hz separated by commas, e.g. 1000000:2000, 2500000. Omitted half width = 2000 Hz. For clock leakage, supply spurs or a fixed reflection."),
      _T("Смуги частот, які ігноруються, у вигляді 'центр:півширина' у Гц через кому, напр. 1000000:2000, 2500000. Пропущена півширина = 2000 Гц. Для протікання тактової частоти, завад живлення або постійного відбиття.") },
    { IDC_BTN_LEARN_SPURS, _T("Add every peak detected in the current frame to the ignore list. Use it with nothing in front of the antenna, so the fixed spurious lines are ignored afterwards."),
      _T("Додати всі піки поточного кадру до списку ігнорованих частот. Натискайте, коли перед антеною нічого немає, тоді постійні завади далі не заважатимуть.") },
    { IDC_BTN_CLEAR_SPURS, _T("Empty the ignore list."), _T("Очистити список ігнорованих частот.") },
    { IDC_EDT_DBTOP, _T("Top of the dB axis on the spectrum and of the colour scale, dBFS (0 = full-scale sine). Default 0."),
      _T("Верхня межа шкали дБ на спектрі та шкали кольорів, дБFS (0 = синусоїда на повну шкалу АЦП). Типово 0.") },
    { IDC_EDT_DBBOTTOM, _T("Bottom of the dB axis, dBFS. Default -120."), _T("Нижня межа шкали дБ, дБFS. Типово -120.") },
    { IDC_EDT_WF_ROWS, _T("History depth of the waterfall in frames (64..4096). Default 512."), _T("Скільки останніх кадрів зберігає водоспад (64..4096). Типово 512.") },
    { IDC_EDT_ADCBITS, _T("ADC resolution used to convert codes to volts on the Scope tab. Default 12."), _T("Розрядність АЦП для перерахунку кодів у вольти на вкладці Осцилограф. Типово 12.") },
    { IDC_EDT_VREF, _T("ADC full-scale voltage for the volts scale on the Scope tab. Default 3.3 V."), _T("Напруга повної шкали АЦП для шкали у вольтах на вкладці Осцилограф. Типово 3.3 В.") },
    { IDC_BTN_DEFAULTS, _T("Reset the processing, detection and display settings of this column to their defaults (MCU and radar settings are kept)."),
      _T("Скинути налаштування обробки, виявлення та відображення цієї колонки до типових (налаштування МК і радара зберігаються).") },

    // Radar footer
    { IDC_CMB_TRACE, _T("How successive spectra are combined. No accumulation: every frame as is. Averaging: exponential average, steadier noise floor. Max / Min hold: envelope over time."),
      _T("Як поєднуються спектри послідовних кадрів. Без накопичення: кожен кадр як є. Усереднення: експоненційне середнє, спокійніший шум. Утримання максимуму / мінімуму: огинаюча в часі.") },
    { IDC_CMB_WF_PALETTE, _T("Colour palette of the waterfall and the range-velocity map."), _T("Палітра кольорів водоспаду та карти дальність-швидкість.") },
    { IDC_CHK_SHOW_UP, _T("Show the UP-ramp spectrum."), _T("Показувати спектр рампи UP.") },
    { IDC_CHK_SHOW_DN, _T("Show the DOWN-ramp spectrum."), _T("Показувати спектр рампи DOWN.") },
    { IDC_CHK_SHOW_THR, _T("Show the detection threshold line."), _T("Показувати лінію порога виявлення.") },
    { IDC_CHK_SHOW_NOISE, _T("Show the noise estimate line."), _T("Показувати лінію оцінки шуму.") },
    { IDC_CHK_SHOW_RD, _T("Show the range-velocity map next to the waterfall (needs more than one chirp per frame)."), _T("Показувати карту дальність-швидкість поруч із водоспадом (потрібно більше одного чірпа в кадрі).") },
    { IDC_BTN_RESET_AVG, _T("Restart the accumulation, phase tracking and target tracks. Key: A."), _T("Почати накопичення, відлік фази та супровід цілей заново. Клавіша A.") },
    { IDC_BTN_AUTOSCALE, _T("Fit the dB axis and the colour scale to the current data."), _T("Підігнати шкалу дБ і шкалу кольорів під поточні дані.") },
    { IDC_BTN_CLEAR_WF, _T("Clear the waterfall history."), _T("Очистити історію водоспаду.") },

    // Scope footer
    { IDC_CHK_DOTS, _T("Draw individual samples as dots instead of a line."), _T("Малювати окремі відліки точками замість лінії.") },
    { IDC_RDO_VOLTS, _T("Vertical scale in volts (ADC bits and full scale from the Radar tab settings)."), _T("Вертикальна шкала у вольтах (розрядність і опорна напруга з налаштувань на вкладці Радар).") },
    { IDC_RDO_CODES, _T("Vertical scale in raw ADC codes."), _T("Вертикальна шкала у кодах АЦП.") },
    { IDC_CMB_RAMP_SEL, _T("Which ramp of the frame is shown in the detail view below."), _T("Яка рампа кадру показується у нижньому вікні.") },

    // Communication footer
    { IDC_CMB_LOG_FILTER, _T("Show only log lines of one kind."), _T("Показувати лише рядки журналу одного типу.") },
    { IDC_CHK_LOG_VERBOSE, _T("Log every received frame (one line per frame)."), _T("Записувати кожен прийнятий кадр (рядок на кадр).") },
    { IDC_CHK_LOG_SCROLL, _T("Keep the newest line in view."), _T("Тримати найновіший рядок на видноті.") },
    { IDC_BTN_LOG_COPY, _T("Copy the selected lines (or all) to the clipboard."), _T("Копіювати вибрані рядки (або всі) у буфер обміну.") },
    { IDC_BTN_LOG_SAVE, _T("Save the log to a text file."), _T("Зберегти журнал у текстовий файл.") },
    { IDC_BTN_LOG_CLEAR, _T("Clear the log."), _T("Очистити журнал.") },

    // Trace tab
    { IDC_TRC_CHK_ENABLE, _T("Enable the step-by-step acquisition trace inside the firmware (CMD_SET_TRACE). Each capture then sends a TRACE frame with its timeline."),
      _T("Увімкнути покрокове трасування захоплення у прошивці (CMD_SET_TRACE). Після кожного захоплення МК надсилає TRACE-кадр із хронологією подій.") },
    { IDC_TRC_BTN_SHOT, _T("Switch the device to Single mode and trigger one capture (one traced cycle)."), _T("Перевести пристрій в одиночний режим і зробити одне захоплення (один трасований цикл).") },
    { IDC_TRC_BTN_GET, _T("Ask the device to send its trace buffer now (CMD_GET_TRACE)."), _T("Попросити пристрій надіслати буфер трасування зараз (CMD_GET_TRACE).") },
    { IDC_TRC_BTN_CLEAR, _T("Clear the trace list."), _T("Очистити список траси.") },
    { IDC_TRC_BTN_EXPORT, _T("Export the trace records to a CSV file."), _T("Експортувати записи траси у файл CSV.") },
};

std::map<CString, CString>& Table()
{
    static std::map<CString, CString> t;
    if (t.empty()) for (const auto& e : kStrings) t[e.en] = e.uk;
    return t;
}

} // namespace

void Set(Id id) { g_lang = (id == Id::Ukrainian) ? Id::Ukrainian : Id::English; }
Id   Get()      { return g_lang; }

LPCTSTR Name(Id id) { return id == Id::Ukrainian ? _T("Українська") : _T("English"); }

CString Tr(LPCTSTR english)
{
    if (!english) return CString();
    if (g_lang == Id::English) return CString(english);
    const auto& t = Table();
    auto it = t.find(CString(english));
    return (it != t.end()) ? it->second : CString(english);
}

CString Help(UINT ctrlId)
{
    for (const auto& h : kHelp)
        if (h.id == ctrlId) return CString(g_lang == Id::Ukrainian ? h.uk : h.en);
    return CString();
}

void TranslateMenu(CMenu* menu)
{
    if (!menu || !menu->GetSafeHmenu()) return;
    const UINT n = menu->GetMenuItemCount();
    for (UINT i = 0; i < n; ++i) {
        CString text;
        menu->GetMenuString(i, text, MF_BYPOSITION);
        if (text.IsEmpty()) continue;
        const CString tr = Tr(text);
        CMenu* sub = menu->GetSubMenu(static_cast<int>(i));
        if (sub) {
            if (tr != text) menu->ModifyMenu(i, MF_BYPOSITION | MF_STRING | MF_POPUP, reinterpret_cast<UINT_PTR>(sub->GetSafeHmenu()), tr);
            TranslateMenu(sub);
        } else {
            const UINT id = menu->GetMenuItemID(static_cast<int>(i));
            if (tr != text && id != static_cast<UINT>(-1)) menu->ModifyMenu(i, MF_BYPOSITION | MF_STRING, id, tr);
        }
    }
}

} // namespace Lang
