#include "pch.h"
#include "Lang.h"
#include "resource.h"

#include <map>

namespace Lang {

namespace {

Id g_lang = Id::English;

struct Entry { LPCTSTR en; LPCTSTR uk; };

// ---------------------------------------------------------------------------
// UI strings. Format specifiers must be kept in the translation.
// ---------------------------------------------------------------------------
const Entry kStrings[] = {
    // Tabs / menu
    { _T("Radar"), _T("Радар") },
    { _T("Scope"), _T("Осцилограф") },
    { _T("Communication"), _T("Зв'язок") },
    { _T("Settings"), _T("Налаштування") },
    { _T("Trace"), _T("Трасування") },
    { _T("&File"), _T("&Файл") },
    { _T("&Open replay...\tCtrl+O"), _T("&Відкрити запис...\tCtrl+O") },
    { _T("&Close replay"), _T("&Закрити запис") },
    { _T("Start/stop &recording\tR"), _T("Почати/зупинити &запис\tR") },
    { _T("&Save frame as CSV...\tCtrl+S"), _T("З&берегти кадр як CSV...\tCtrl+S") },
    { _T("Export &targets as CSV..."), _T("Експорт &цілей у CSV...") },
    { _T("Export IF signal as &WAV..."), _T("Експорт ПЧ-сигналу у &WAV...") },
    { _T("Save screenshot as &PNG...\tF12"), _T("Зберегти знімок екрана як &PNG...\tF12") },
    { _T("E&xit"), _T("Ви&хід") },
    { _T("&Acquisition"), _T("&Захоплення") },
    { _T("&Connect / Disconnect\tF5"), _T("&Підключити / Відключити\tF5") },
    { _T("&Start\tSpace"), _T("&Старт\tПробіл") },
    { _T("S&top\tSpace"), _T("С&топ\tПробіл") },
    { _T("&Trigger\tT"), _T("&Тригер\tT") },
    { _T("&Abort"), _T("&Перервати") },
    { _T("&Hold / Live\tH"), _T("&Зафіксувати / Наживо\tH") },
    { _T("&Reset averages\tA"), _T("С&кинути усереднення\tA") },
    { _T("&Ping"), _T("&Ping") },
    { _T("Get &status"), _T("Отримати &статус") },
    { _T("&View"), _T("&Вигляд") },
    { _T("&Radar\tCtrl+1"), _T("&Радар\tCtrl+1") },
    { _T("&Scope\tCtrl+2"), _T("&Осцилограф\tCtrl+2") },
    { _T("&Communication\tCtrl+3"), _T("&Зв'язок\tCtrl+3") },
    { _T("S&ettings\tCtrl+4"), _T("&Налаштування\tCtrl+4") },
    { _T("&Trace\tCtrl+5"), _T("&Трасування\tCtrl+5") },
    { _T("&Dark theme"), _T("&Темна тема") },
    { _T("&Help"), _T("&Довідка") },
    { _T("&Keyboard shortcuts"), _T("&Гарячі клавіші") },
    { _T("&About FastAcq"), _T("&Про FastAcq") },

    // Command panel
    { _T("Connect"), _T("Підключити") },
    { _T("Disconnect"), _T("Відключити") },
    { _T("Start"), _T("Старт") },
    { _T("Stop"), _T("Стоп") },
    { _T("Trigger"), _T("Тригер") },
    { _T("Abort"), _T("Перервати") },
    { _T("Hold"), _T("Фіксація") },
    { _T("⏸ Hold"), _T("⏸ Фіксація") },
    { _T("▶ Live"), _T("▶ Наживо") },
    { _T("● Record"), _T("● Запис") },
    { _T("■ Stop rec"), _T("■ Стоп запису") },
    { _T("Open..."), _T("Відкрити...") },
    { _T("Save frame"), _T("Зберегти кадр") },
    { _T("Clear"), _T("Очистити") },
    { _T("Replay"), _T("Відтворення") },
    { _T("Play"), _T("Грати") },
    { _T("Pause"), _T("Пауза") },
    { _T("Close"), _T("Закрити") },
    { _T("max"), _T("макс") },

    // Settings tab
    { _T("MCU acquisition"), _T("Захоплення МК") },
    { _T("Mode"), _T("Режим") },
    { _T("Idle"), _T("Очікування") },
    { _T("Continuous"), _T("Безперервний") },
    { _T("Single"), _T("Одиночний") },
    { _T("Apply"), _T("Застосувати") },
    { _T("Set"), _T("Задати") },
    { _T("Chirp freq, Hz (100..24000)"), _T("Частота чірпа, Гц (100..24000)") },
    { _T("Samples (0 = auto)"), _T("Відліків (0 = авто)") },
    { _T("Interval, ms"), _T("Інтервал, мс") },
    { _T("Chirp amplitude, DAC"), _T("Амплітуда чірпа, DAC") },
    { _T("Chirp offset (base), DAC"), _T("Зміщення чірпа (база), DAC") },
    { _T("Chirps per capture"), _T("Чірпів у захопленні") },
    { _T("Ramp rise / fall, us"), _T("Рампа підйом / спад, мкс") },
    { _T("Set ramp"), _T("Задати рампу") },
    { _T("Frame content"), _T("Вміст кадру") },
    { _T("Raw"), _T("Сирі") },
    { _T("FFT"), _T("FFT") },
    { _T("Ping"), _T("Ping") },
    { _T("Get status"), _T("Статус") },
    { _T("Send all"), _T("Надіслати все") },
    { _T("Radar geometry"), _T("Геометрія радара") },
    { _T("VCO (HMC431)"), _T("VCO (HMC431)") },
    { _T("f0 / B from tuning curve"), _T("f0 / B з кривої налаштування") },
    { _T("Vtune at DAC 0 / 4095, V"), _T("Vtune при DAC 0 / 4095, В") },
    { _T("Tuning curve V:GHz,..."), _T("Крива налаштування В:ГГц,...") },
    { _T("Carrier f0 (sweep centre), GHz"), _T("Несуча f0 (центр свіпу), ГГц") },
    { _T("Sweep bandwidth B, MHz"), _T("Смуга свіпу B, МГц") },
    { _T("Ramp time, ms (0 = auto)"), _T("Час рампи, мс (0 = авто)") },
    { _T("Range offset, m"), _T("Зміщення дальності, м") },
    { _T("Modulation"), _T("Модуляція") },
    { _T("Chirps per frame"), _T("Чірпів у кадрі") },
    { _T("= burst"), _T("= burst") },
    { _T("UP/DOWN pair gate, m/s"), _T("Ворота пари UP/DOWN, м/с") },
    { _T("Application"), _T("Програма") },
    { _T("Theme"), _T("Тема") },
    { _T("Dark"), _T("Темна") },
    { _T("Language"), _T("Мова") },
    { _T("Fallback Fs, Hz"), _T("Резервна Fs, Гц") },
    { _T("ADC clock corr., ppm"), _T("Корекція тактів АЦП, ppm") },
    { _T("Log"), _T("Журнал") },
    { _T("Per-frame RX lines"), _T("Рядок RX на кожен кадр") },
    { _T("Start-up"), _T("Запуск") },
    { _T("Auto-connect"), _T("Автопідключення") },
    { _T("Derived values"), _T("Похідні значення") },
    { _T("The language changes after the application is restarted."), _T("Мова зміниться після перезапуску програми.") },
    { _T("VCO: DAC %d..%d = Vtune %.2f..%.2f V -> %.4f..%.4f GHz, B %.1f MHz, %.0f..%.0f MHz/V, nonlin. %.1f%%%s\r\n"),
      _T("VCO: DAC %d..%d = Vtune %.2f..%.2f В -> %.4f..%.4f ГГц, B %.1f МГц, %.0f..%.0f МГц/В, нелін. %.1f%%%s\r\n") },
    { _T(" [Vtune outside the curve table!]"), _T(" [Vtune поза таблицею кривої!]") },
    { _T("VCO: tuning curve invalid (need >= 2 points V:GHz)\r\n"), _T("VCO: крива невалідна (потрібно >= 2 точок В:ГГц)\r\n") },
    { _T("Ramp %.4f ms, period %.4f ms\r\n"), _T("Рампа %.4f мс, період %.4f мс\r\n") },
    { _T("%zu samples/ramp, %zu used\r\n"), _T("%zu відліків/рампа, %zu використано\r\n") },
    { _T("Decimation x%d: Fs_eff %.1f kHz, FFT %zu\r\n"), _T("Децимація x%d: Fs_eff %.1f кГц, FFT %zu\r\n") },
    { _T("Bin %.1f Hz"), _T("Бін %.1f Гц") },
    { _T(" = %.3f m"), _T(" = %.3f м") },
    { _T("Range res. c/2B %.3f m (eff. %.3f m), R_max %.1f m\r\n"), _T("Розд. здатн. c/2B %.3f м (еф. %.3f м), R_max %.1f м\r\n") },
    { _T("Beat %.1f Hz per metre\r\n"), _T("Биття %.1f Гц на метр\r\n") },
    { _T("Range axis: set bandwidth B > 0\r\n"), _T("Вісь дальності: задайте смугу B > 0\r\n") },
    { _T("Velocity res. %.3f m/s (burst %d), max +/- %.2f m/s\r\n"), _T("Розд. швидкості %.3f м/с (burst %d), макс +/- %.2f м/с\r\n") },
    { _T("USB %.2f MB/s at %d ms (FS CDC limit ~0.8 MB/s)"), _T("USB %.2f МБ/с при %d мс (межа FS CDC ~0.8 МБ/с)") },
    { _T("\r\nADC clock %+.3f ppm: %.6f -> %.6f MS/s"), _T("\r\nТакт АЦП %+.3f ppm: %.6f -> %.6f МВ/с") },

    // Processing panel
    { _T("Processing"), _T("Обробка") },
    { _T("Spectrum source"), _T("Джерело спектра") },
    { _T("RAW on PC"), _T("RAW на ПК") },
    { _T("MCU FFT"), _T("FFT з МК") },
    { _T("Ramp guard, % each end"), _T("Захист рампи, % з краю") },
    { _T("Detrend"), _T("Тренд") },
    { _T("Remove linear trend"), _T("Прибрати лінійний тренд") },
    { _T("Decimation"), _T("Децимація") },
    { _T("Auto"), _T("Авто") },
    { _T("Range of interest, m"), _T("Дальність інтересу, м") },
    { _T("Window"), _T("Вікно") },
    { _T("Kaiser beta"), _T("Кайзер beta") },
    { _T("Zero padding"), _T("Доповнення нулями") },
    { _T("Range gain"), _T("Підсилення по дальності") },
    { _T("Off"), _T("Вимк.") },
    { _T("20 dB/dec (R^2)"), _T("20 дБ/дек (R^2)") },
    { _T("40 dB/dec (R^4)"), _T("40 дБ/дек (R^4)") },
    { _T("Chirp split"), _T("Поділ чірпа") },
    { _T("From frame header"), _T("З заголовка кадру") },
    { _T("Tone estimate"), _T("Оцінка тону") },
    { _T("Precise (double FFT)"), _T("Точна (double FFT)") },
    { _T("Detection"), _T("Виявлення") },
    { _T("Detector"), _T("Детектор") },
    { _T("Threshold above noise, dB"), _T("Поріг над шумом, дБ") },
    { _T("CFAR false-alarm prob."), _T("Ймов. хибної тривоги CFAR") },
    { _T("0.01  (1 in 100)"), _T("0.01  (1 на 100)") },
    { _T("0.001  (1 in 1000)"), _T("0.001  (1 на 1000)") },
    { _T("0.0001  (1 in 10 000)"), _T("0.0001  (1 на 10 000)") },
    { _T("0.00001  (1 in 100 000)"), _T("0.00001  (1 на 100 000)") },
    { _T("0.000001  (1 in 1 000 000)"), _T("0.000001  (1 на 1 000 000)") },
    { _T("CFAR guard cells"), _T("Захисні комірки CFAR") },
    { _T("CFAR training cells"), _T("Опорні комірки CFAR") },
    { _T("Peak interpolation"), _T("Інтерполяція піка") },
    { _T("Max targets"), _T("Макс. цілей") },
    { _T("Doppler"), _T("Доплер") },
    { _T("MTI (subtract mean)"), _T("MTI (відняти середнє)") },
    { _T("Tracking"), _T("Супровід") },
    { _T("Stable target IDs"), _T("Стабільні ID цілей") },
    { _T("Rejection"), _T("Відкидання") },
    { _T("Harmonics"), _T("Гармоніки") },
    { _T("Drop 2f, 3f.. of a stronger peak"), _T("Відкидати 2f, 3f.. сильнішого піка") },
    { _T("Harmonic weaker by, dB"), _T("Гармоніка слабша на, дБ") },
    { _T("Min SNR, dB (0 = off)"), _T("Мін. SNR, дБ (0 = вимк.)") },
    { _T("Confirm after N frames"), _T("Підтвердити після N кадрів") },
    { _T("Spur mask Hz:halfwidth,..."), _T("Маска завад Гц:півширина,...") },
    { _T("Learn spurs"), _T("Запам'ятати завади") },
    { _T("Display"), _T("Відображення") },
    { _T("dB axis top"), _T("Вісь дБ, верх") },
    { _T("dB axis bottom"), _T("Вісь дБ, низ") },
    { _T("Waterfall rows"), _T("Рядків водоспаду") },
    { _T("ADC bits"), _T("Розрядність АЦП") },
    { _T("ADC full scale, V"), _T("Повна шкала АЦП, В") },
    { _T("Defaults"), _T("За замовчуванням") },

    // Radar tab
    { _T("Trace:"), _T("Траса:") },
    { _T("Palette:"), _T("Палітра:") },
    { _T("UP"), _T("UP") },
    { _T("DOWN"), _T("DOWN") },
    { _T("Threshold"), _T("Поріг") },
    { _T("Noise"), _T("Шум") },
    { _T("Range-Doppler"), _T("Дальність-Доплер") },
    { _T("Reset avg"), _T("Скинути усер.") },
    { _T("Autoscale"), _T("Автомасштаб") },
    { _T("Clear WF"), _T("Очистити ВС") },
    { _T("Phase @ %s: %+.3f mm"), _T("Фаза @ %s: %+.3f мм") },
    { _T("Range profile"), _T("Профіль дальності") },
    { _T("Waterfall (range - time)"), _T("Водоспад (дальність - час)") },
    { _T("Range - Doppler"), _T("Дальність - Доплер") },
    { _T("no data"), _T("немає даних") },
    { _T("threshold"), _T("поріг") },
    { _T("noise"), _T("шум") },
    { _T("frame %u   t = %u ms   bin %.1f Hz"), _T("кадр %u   t = %u мс   бін %.1f Гц") },
    { _T("   fs/%d = %s   N = %zu   DSP %.1f ms"), _T("   fs/%d = %s   N = %zu   DSP %.1f мс") },
    { _T("   [MCU FFT]"), _T("   [FFT з МК]") },
    { _T("   rejected: %d harmonic, %d spur, %d low SNR, %d unconfirmed"), _T("   відкинуто: %d гармонік, %d завад, %d низький SNR, %d непідтверджених") },
    { _T("Reset zoom\tHome"), _T("Скинути масштаб\tHome") },
    { _T("Reset zoom"), _T("Скинути масштаб") },
    { _T("Autoscale dB\tA"), _T("Автомасштаб дБ\tA") },
    { _T("Autoscale colours"), _T("Автомасштаб кольорів") },
    { _T("Markers on two strongest peaks"), _T("Маркери на два найсильніші піки") },
    { _T("Clear markers\tEsc"), _T("Прибрати маркери\tEsc") },
    { _T("Clear cursors\tEsc"), _T("Прибрати курсори\tEsc") },
    { _T("Clear history"), _T("Очистити історію") },
    { _T("Copy image"), _T("Копіювати зображення") },
    { _T("needs chirps per frame > 1 (burst)"), _T("потрібно > 1 чірпа в кадрі (burst)") },
    { _T("%zu rows   palette %s"), _T("%zu рядків   палітра %s") },
    { _T("%d chirps   %d x %d   v bin %.3f m/s   v max %.2f m/s"), _T("%d чірпів   %d x %d   бін v %.3f м/с   v макс %.2f м/с") },

    // Target / frame lists
    { _T("R, m"), _T("R, м") },
    { _T("v, m/s"), _T("v, м/с") },
    { _T("f_up, kHz"), _T("f_up, кГц") },
    { _T("f_dn, kHz"), _T("f_dn, кГц") },
    { _T("A, dBFS"), _T("A, дБFS") },
    { _T("SNR, dB"), _T("SNR, дБ") },
    { _T("pair"), _T("пара") },
    { _T("yes"), _T("так") },
    { _T("no"), _T("ні") },
    { _T("t, ms"), _T("t, мс") },

    // Scope tab
    { _T("Frame (all chirps)"), _T("Кадр (усі чірпи)") },
    { _T("Ramp detail"), _T("Деталь рампи") },
    { _T("Ramp:"), _T("Рампа:") },
    { _T("Dots"), _T("Точки") },
    { _T("Volts"), _T("Вольти") },
    { _T("ADC codes"), _T("Коди АЦП") },
    { _T("Frame %u  (%zu samples, %d chirps)"), _T("Кадр %u  (%zu відліків, %d чірпів)") },
    { _T("  UP %zu + DOWN %zu smp"), _T("  UP %zu + DOWN %zu відл.") },
    { _T(", %zu after the last chirp (unused)"), _T(", %zu після останнього чірпа (не використано)") },
    { _T("Ramp detail: %s #%d  (%zu samples in the ramp"), _T("Деталь рампи: %s #%d  (%zu відліків у рампі") },
    { _T(", %.1f beat cycles of %s"), _T(", %.1f періодів биття по %s") },
    { _T(", %.1f cycles of %s"), _T(", %.1f періодів по %s") },
    { _T(", +%zu guard"), _T(", +%zu захисних") },
    { _T("guard %zu smp"), _T("захист %zu відл.") },
    { _T("%s #%d: %zu smp, %s"), _T("%s #%d: %zu відл., %s") },
    { _T("   tone UP %.1f Hz"), _T("   тон UP %.1f Гц") },
    { _T(" / DOWN %.1f Hz"), _T(" / DOWN %.1f Гц") },
    { _T("   MCU peak %.1f Hz"), _T("   пік МК %.1f Гц") },
    { _T("   decim x%d, fs_eff %s, ramp %s%s"), _T("   децим. x%d, fs_eff %s, рампа %s%s") },
    { _T(" (hdr)"), _T(" (заг.)") },

    // Communication tab
    { _T("Time"), _T("Час") },
    { _T("Kind"), _T("Тип") },
    { _T("Message"), _T("Повідомлення") },
    { _T("All"), _T("Усі") },
    { _T("Errors"), _T("Помилки") },
    { _T("Service (ACK/STATUS/PONG)"), _T("Службові (ACK/STATUS/PONG)") },
    { _T("Port / info"), _T("Порт / інфо") },
    { _T("Auto-scroll"), _T("Автопрокрутка") },
    { _T("Copy"), _T("Копіювати") },
    { _T("Save..."), _T("Зберегти...") },
    { _T("Cannot write the log file."), _T("Не вдалося записати файл журналу.") },
    { _T("Text files (*.txt)|*.txt|All files (*.*)|*.*||"), _T("Текстові файли (*.txt)|*.txt|Усі файли (*.*)|*.*||") },

    // Trace tab
    { _T("Trace enabled (MCU test mode)"), _T("Трасування увімкнено (тестовий режим МК)") },
    { _T("Trace not compiled into firmware"), _T("Трасування не вбудоване у прошивку") },
    { _T("Single shot"), _T("Один постріл") },
    { _T("Get trace"), _T("Отримати трасу") },
    { _T("Export CSV..."), _T("Експорт CSV...") },
    { _T("No trace received. Enable trace, then fire a single shot."), _T("Траса не отримана. Увімкніть трасування і зробіть один постріл.") },
    { _T("No trace to export."), _T("Немає траси для експорту.") },
    { _T("Cleared."), _T("Очищено.") },
    { _T("Cannot create file."), _T("Не вдалося створити файл.") },
    { _T("CSV files (*.csv)|*.csv|All files (*.*)|*.*||"), _T("Файли CSV (*.csv)|*.csv|Усі файли (*.*)|*.*||") },
    { _T("t, us"), _T("t, мкс") },
    { _T("dt, us"), _T("dt, мкс") },
    { _T("tick, ms"), _T("тік, мс") },
    { _T("ctx"), _T("ктх") },
    { _T("event"), _T("подія") },
    { _T("details"), _T("деталі") },
    { _T("%u records (%u dropped), span %u.%03u ms, capture tick %u ms, chirp %u Hz, amp %u, burst %u, rise/fall %u/%u us"),
      _T("%u записів (%u втрачено), тривалість %u.%03u мс, тік захоплення %u мс, чірп %u Гц, амп %u, burst %u, підйом/спад %u/%u мкс") },

    // Main frame / status bar / dialogs
    { _T("Disconnected"), _T("Відключено") },
    { _T("Connected %s  %s%s"), _T("Підключено %s  %s%s") },
    { _T("RUNNING"), _T("ПРАЦЮЄ") },
    { _T("idle"), _T("очікування") },
    { _T("  [HOLD]"), _T("  [ФІКСАЦІЯ]") },
    { _T("  ● REC"), _T("  ● ЗАПИС") },
    { _T("Replay %s  (%zu / %zu)"), _T("Відтворення %s  (%zu / %zu)") },
    { _T("MCU: -"), _T("МК: -") },
    { _T("Fs %.4f MS/s  %zu smp  %.1f fps  %.2f MB/s  RTT %lu ms"), _T("Fs %.4f МВ/с  %zu відл.  %.1f к/с  %.2f МБ/с  RTT %lu мс") },
    { _T("lost %llu  CRC %llu  hdr %llu"), _T("втрачено %llu  CRC %llu  заг. %llu") },
    { _T("DSP %.1f ms"), _T("DSP %.1f мс") },
    { _T("buf %zu/%zu  %.0f MB"), _T("буф %zu/%zu  %.0f МБ") },
    { _T("MCU rejected command 0x%02X: %s"), _T("МК відхилив команду 0x%02X: %s") },
    { _T("Select a COM port first."), _T("Спочатку виберіть COM-порт.") },
    { _T("Failed to open %s"), _T("Не вдалося відкрити %s") },
    { _T("No frame to save."), _T("Немає кадру для збереження.") },
    { _T("No frames in the buffer."), _T("У буфері немає кадрів.") },
    { _T("No raw samples in the current frame."), _T("У поточному кадрі немає сирих відліків.") },
    { _T("Save failed."), _T("Збереження не вдалося.") },
    { _T("WAV export failed."), _T("Експорт WAV не вдався.") },
    { _T("Screenshot failed."), _T("Знімок екрана не вдався.") },
    { _T("Close the replay before recording."), _T("Закрийте відтворення перед записом.") },
    { _T("Cannot create the session file."), _T("Не вдалося створити файл сесії.") },
    { _T("Cannot open the session file."), _T("Не вдалося відкрити файл сесії.") },
    { _T("Recording started: "), _T("Запис розпочато: ") },
    { _T("Recording stopped: %llu frames"), _T("Запис зупинено: %llu кадрів") },
    { _T("Recording: write failed, stopping"), _T("Запис: помилка запису, зупинка") },
    { _T("REC %s  %llu frames  %.1f MB"), _T("ЗАПИС %s  %llu кадрів  %.1f МБ") },
    { _T("Replay opened: %s (%zu frames, Fs %u Hz)"), _T("Відтворення відкрито: %s (%zu кадрів, Fs %u Гц)") },
    { _T("FastAcq sessions (*.facq)|*.facq|All files (*.*)|*.*||"), _T("Сесії FastAcq (*.facq)|*.facq|Усі файли (*.*)|*.*||") },
    { _T("WAV files (*.wav)|*.wav|All files (*.*)|*.*||"), _T("Файли WAV (*.wav)|*.wav|Усі файли (*.*)|*.*||") },
    { _T("PNG images (*.png)|*.png||"), _T("Зображення PNG (*.png)|*.png||") },
    { _T("TRACE %u records, %u dropped (see Trace tab)"), _T("ТРАСА %u записів, %u втрачено (див. вкладку Трасування)") },
    { _T("FastAcq 2.0\n\nFMCW radar IF-signal analyzer for the STM32H7 Fast Acquisition Device.\n"),
      _T("FastAcq 2.0\n\nАналізатор ПЧ-сигналу FMCW-радара для пристрою STM32H7 Fast Acquisition.\n") },
    { _T("C++17 / MFC / GDI, no third-party dependencies.\n\nMIT License."), _T("C++17 / MFC / GDI, без сторонніх залежностей.\n\nЛіцензія MIT.") },
    { _T("Space\tStart / Stop acquisition\n"), _T("Пробіл\tСтарт / Стоп захоплення\n") },
    { _T("T\tTrigger a single capture\n"), _T("T\tОдиночне захоплення (тригер)\n") },
    { _T("H\tHold / Live display\n"), _T("H\tФіксація / Наживо\n") },
    { _T("R\tStart / stop recording\n"), _T("R\tПочати / зупинити запис\n") },
    { _T("F5\tConnect / disconnect\n"), _T("F5\tПідключити / відключити\n") },
    { _T("Ctrl+O\tOpen replay\n"), _T("Ctrl+O\tВідкрити запис\n") },
    { _T("Ctrl+S\tSave frame as CSV\n"), _T("Ctrl+S\tЗберегти кадр як CSV\n") },
    { _T("F12\tSave screenshot (PNG)\n"), _T("F12\tЗнімок екрана (PNG)\n") },
    { _T("Ctrl+1..5\tSwitch tab\n"), _T("Ctrl+1..5\tПеремкнути вкладку\n") },
    { _T("PgUp / PgDn, Ctrl+Left / Right\tPrevious / next frame\n\n"), _T("PgUp / PgDn, Ctrl+Вліво / Вправо\tПопередній / наступний кадр\n\n") },
    { _T("In plots: wheel = zoom at cursor, Shift+wheel = pan, drag = pan, double-click = reset,\n"),
      _T("На графіках: колесо = масштаб під курсором, Shift+колесо = зсув, перетягування = зсув, подвійний клік = скинути,\n") },
    { _T("click = marker A, Shift+click = marker B, Esc = clear markers, Home = reset zoom, A = autoscale dB."),
      _T("клік = маркер A, Shift+клік = маркер B, Esc = прибрати маркери, Home = скинути масштаб, A = автомасштаб дБ.") },

    // Chirp preview
    { _T("Chirp preview (what the MCU will generate)"), _T("Попередній перегляд чірпа (що згенерує МК)") },
    { _T("Parameters out of range: frequency 100..24000 Hz, period 41.7 us .. 10 ms."), _T("Параметри поза межами: частота 100..24000 Гц, період 41.7 мкс .. 10 мс.") },
    { _T("DAC code"), _T("Код DAC") },
    { _T("Vtune  /  VCO out"), _T("Vtune  /  вихід VCO") },
    { _T("Vtune"), _T("Vtune") },
    { _T("next cycle"), _T("наст. цикл") },
    { _T("rise "), _T("підйом ") },
    { _T("fall "), _T("спад ") },
    { _T("burst x%u%s"), _T("burst x%u%s") },
    { _T(" (first 4 drawn)"), _T(" (намальовано 4)") },
    { _T("interval %u ms"), _T("інтервал %u мс") },
    { _T("wait TRIGGER"), _T("очікує TRIGGER") },
    { _T("IDLE: trigger only"), _T("IDLE: лише тригер") },
    { _T("T = %s   f = %.3f Hz   (%s)"), _T("T = %s   f = %.3f Гц   (%s)") },
    { _T("ramp mode: rise/fall"), _T("режим рампи: підйом/спад") },
    { _T("freq mode: symmetric"), _T("режим частоти: симетрично") },
    { _T("ADC @ %.0f MS/s: chirp = rise %u + fall %u = %u samples (%s)"), _T("АЦП @ %.0f МВ/с: чірп = підйом %u + спад %u = %u відліків (%s)") },
    { _T(";  burst x%u = %llu samples (%s)"), _T(";  burst x%u = %llu відліків (%s)") },
    { _T("OK: fits in ONE capture window of %u samples (%s, %u DMA chunks x %u) = %.1f chirps; MCU buffer %u samples (%s), %.0f%% used"),
      _T("OK: вміщається в ОДНЕ вікно захоплення %u відліків (%s, %u DMA-блоків x %u) = %.1f чірпів; буфер МК %u відліків (%s), %.0f%% використано") },
    { _T("DOES NOT FIT: samples override %u cuts the burst to %u samples (%s) = %.2f chirps of %u; set samples to 0 (auto) or >= %llu"),
      _T("НЕ ВМІЩАЄТЬСЯ: задані відліки %u обрізають burst до %u відліків (%s) = %.2f чірпів з %u; поставте відліки 0 (авто) або >= %llu") },
    { _T("DOES NOT FIT: burst needs %llu samples (%s), MCU capture holds %u (%s) = %.2f chirps of %u; reduce burst or shorten the chirp"),
      _T("НЕ ВМІЩАЄТЬСЯ: burst потребує %llu відліків (%s), захоплення МК тримає %u (%s) = %.2f чірпів з %u; зменшіть burst або вкоротіть чірп") },
    { _T("DAC %.0f..%.0f (offset %u + A %u): Vtune %.2f..%.2f V = %.3f..%.3f GHz (B %.0f MHz)"),
      _T("DAC %.0f..%.0f (зміщення %u + A %u): Vtune %.2f..%.2f В = %.3f..%.3f ГГц (B %.0f МГц)") },
    { _T("DAC %.0f..%.0f (offset %u + A %u): Vtune %.2f..%.2f V"), _T("DAC %.0f..%.0f (зміщення %u + A %u): Vtune %.2f..%.2f В") },
};

// ---------------------------------------------------------------------------
// Tooltips for input controls: what the field is, what it changes, how to
// choose it, and the default value.
// ---------------------------------------------------------------------------
struct HelpEntry { UINT id; LPCTSTR en; LPCTSTR uk; };

const HelpEntry kHelp[] = {
    // Command panel
    { IDC_CMB_COM, _T("Serial (USB CDC) port of the FastAcq device. The list is refreshed when devices are plugged in; FastAcq ports are listed first."),
      _T("Послідовний порт (USB CDC) пристрою FastAcq. Список оновлюється при підключенні; порти FastAcq ідуть першими.") },
    { IDC_BTN_CONNECT, _T("Open / close the selected port. After connecting the device status is read (GET_STATUS) and mirrored into the Settings tab."),
      _T("Відкрити / закрити вибраний порт. Після підключення читається статус пристрою (GET_STATUS) і відображається на вкладці Налаштування.") },
    { IDC_BTN_START, _T("Start continuous acquisition (SET_MODE CONTINUOUS): the MCU captures a frame every 'Interval' ms."),
      _T("Почати безперервне захоплення (SET_MODE CONTINUOUS): МК захоплює кадр кожні 'Інтервал' мс.") },
    { IDC_BTN_STOP, _T("Stop acquisition (SET_MODE IDLE). Captured frames stay in the buffer."),
      _T("Зупинити захоплення (SET_MODE IDLE). Захоплені кадри лишаються в буфері.") },
    { IDC_BTN_TRIGGER, _T("Capture one frame now (TRIGGER). Works in IDLE and SINGLE modes."),
      _T("Захопити один кадр зараз (TRIGGER). Працює в режимах IDLE і SINGLE.") },
    { IDC_BTN_ABORT, _T("Abort the capture in progress immediately."), _T("Негайно перервати поточне захоплення.") },
    { IDC_BTN_HOLD, _T("Hold freezes the display on the current frame (new frames are still buffered and recorded); Live follows the stream again. Key: H."),
      _T("Фіксація зупиняє відображення на поточному кадрі (нові кадри далі буферизуються і записуються); Наживо знову слідує за потоком. Клавіша: H.") },
    { IDC_BTN_RECORD, _T("Start / stop recording every received frame into a .facq session file for later replay. Key: R."),
      _T("Почати / зупинити запис кожного прийнятого кадру у файл сесії .facq для подальшого відтворення. Клавіша: R.") },
    { IDC_BTN_OPEN_REPLAY, _T("Open a recorded .facq session and replay it through the same processing chain, without hardware."),
      _T("Відкрити записану сесію .facq і відтворити її через той самий ланцюг обробки, без обладнання.") },
    { IDC_BTN_SAVE_FRAME, _T("Save the current frame (raw samples and MCU FFT if present) as CSV. Key: Ctrl+S."),
      _T("Зберегти поточний кадр (сирі відліки та FFT МК, якщо є) у CSV. Клавіша: Ctrl+S.") },
    { IDC_BTN_CLEAR, _T("Clear the frame buffer, the waterfall history and the averages."),
      _T("Очистити буфер кадрів, історію водоспаду та усереднення.") },
    { IDC_CMB_RP_SPEED, _T("Replay speed relative to the recorded timing; 'max' plays as fast as the processing allows."),
      _T("Швидкість відтворення відносно записаного часу; 'макс' грає так швидко, як дозволяє обробка.") },
    { IDC_SLD_RP_POS, _T("Position in the replayed session; drag to seek."), _T("Позиція у відтворюваній сесії; перетягніть для переходу.") },

    // Settings: MCU acquisition
    { IDC_CMB_MODE, _T("MCU acquisition mode. Idle: nothing is captured until Trigger. Continuous: a frame every 'Interval' ms (default). Single: one frame per Trigger, then back to waiting."),
      _T("Режим захоплення МК. Очікування: нічого не захоплюється до тригера. Безперервний: кадр кожні 'Інтервал' мс (типово). Одиночний: один кадр на тригер, далі очікування.") },
    { IDC_EDT_FREQ, _T("Chirp repetition frequency, Hz (100..24000). One triangle (rise + fall) per period; the firmware quantizes it to TIM7 ticks, the preview shows the actual value. Typing here leaves the explicit rise/fall ramp mode. Default 458 Hz."),
      _T("Частота повторення чірпа, Гц (100..24000). Один трикутник (підйом + спад) на період; прошивка квантує її у такти TIM7, перегляд показує фактичне значення. Введення тут вимикає режим явної рампи підйом/спад. Типово 458 Гц.") },
    { IDC_EDT_SAMPLES, _T("Capture length override in ADC samples (0 = automatic: one burst of chirps rounded up to a 16384-sample DMA chunk, max 650000). Set it only when you need a fixed length; the preview turns red if it cuts the burst."),
      _T("Примусова довжина захоплення у відліках АЦП (0 = авто: один burst чірпів, округлений до DMA-блоку 16384 відліків, макс 650000). Задавайте лише коли потрібна фіксована довжина; перегляд стає червоним, якщо вона обрізає burst.") },
    { IDC_EDT_INTERVAL, _T("Pause between capture cycles in Continuous mode, ms (5..10000, the firmware minimum is 5). Shorter intervals raise the frame rate and the USB load shown in the derived values. Default 30 ms."),
      _T("Пауза між циклами захоплення у безперервному режимі, мс (5..10000, мінімум прошивки 5). Коротший інтервал збільшує частоту кадрів і навантаження USB (див. похідні значення). Типово 30 мс.") },
    { IDC_EDT_AMPLITUDE, _T("Height of the chirp triangle in DAC counts (1..4095). Together with the offset it sets the tuning-voltage window of the VCO and therefore the swept band B. Default 4095."),
      _T("Висота трикутника чірпа у кодах DAC (1..4095). Разом зі зміщенням задає вікно напруги налаштування VCO і тим самим смугу свіпу B. Типово 4095.") },
    { IDC_EDT_OFFSET, _T("Base level of the chirp in DAC counts (0..4094): the triangle runs from offset to offset + amplitude, i.e. the tuning voltage starts above 0 V. Needs firmware with CMD_SET_OFFSET. Default 0."),
      _T("Базовий рівень чірпа у кодах DAC (0..4094): трикутник іде від зміщення до зміщення + амплітуда, тобто напруга налаштування починається вище 0 В. Потребує прошивки з CMD_SET_OFFSET. Типово 0.") },
    { IDC_EDT_BURST, _T("Chirps captured back-to-back in one frame (1..1024). More than 1 enables the range-Doppler map and velocity resolution; all chirps must fit the MCU buffer (see the preview). Default 1."),
      _T("Кількість чірпів підряд в одному кадрі (1..1024). Більше 1 вмикає карту дальність-Доплер і роздільну здатність по швидкості; всі чірпи мають вміститися в буфер МК (див. перегляд). Типово 1.") },
    { IDC_EDT_RISE, _T("Rise time of the chirp ramp in microseconds. With fall > 0 it switches to the explicit ramp mode (CMD_SET_RAMP) and allows asymmetric triangles; the frequency field mirrors the result. 0/0 = symmetric from the frequency."),
      _T("Час підйому рампи чірпа у мікросекундах. Разом зі спадом > 0 вмикає режим явної рампи (CMD_SET_RAMP) і дозволяє несиметричні трикутники; поле частоти показує результат. 0/0 = симетрично з частоти.") },
    { IDC_EDT_FALL, _T("Fall time of the chirp ramp in microseconds (see rise). The DOWN ramp may be shorter than the UP ramp; the processing pairs them with k = T_fall / T_rise."),
      _T("Час спаду рампи чірпа у мікросекундах (див. підйом). Рампа DOWN може бути коротшою за UP; обробка спарює їх з k = T_fall / T_rise.") },
    { IDC_CHK_RAW, _T("Include the raw ADC samples in every frame (needed for processing on the PC). Default on."),
      _T("Включати сирі відліки АЦП у кожен кадр (потрібно для обробки на ПК). Типово увімкнено.") },
    { IDC_CHK_FFT, _T("Include the FFT magnitudes computed on the MCU. Needed for the 'MCU FFT' spectrum source; otherwise it only costs USB bandwidth. Default on."),
      _T("Включати амплітуди FFT, обчислені на МК. Потрібно для джерела спектра 'FFT з МК'; інакше лише витрачає смугу USB. Типово увімкнено.") },
    { IDC_BTN_PING, _T("Send PING and measure the round-trip time to the device."), _T("Надіслати PING і виміряти час обертання до пристрою.") },
    { IDC_BTN_GET_STATUS, _T("Read the device configuration (mode, frequency, ramp, amplitude, burst, interval, trace) and mirror it into these fields."),
      _T("Прочитати конфігурацію пристрою (режим, частота, рампа, амплітуда, burst, інтервал, трасування) і показати її в цих полях.") },
    { IDC_BTN_SEND_ALL, _T("Send every MCU setting on this tab to the device in one go, then read the status back."),
      _T("Надіслати всі налаштування МК з цієї вкладки на пристрій одразу, потім прочитати статус.") },

    // Settings: radar geometry / VCO
    { IDC_CHK_VCO, _T("Derive the carrier f0 and the swept band B from the VCO tuning curve and the chirp DAC window (offset..offset+amplitude) instead of typing them. Default on."),
      _T("Виводити несучу f0 і смугу свіпу B з кривої налаштування VCO та вікна DAC чірпа (зміщення..зміщення+амплітуда) замість ручного вводу. Типово увімкнено.") },
    { IDC_EDT_VTUNE_LO, _T("Tuning voltage that DAC code 0 produces at the VCO (after the driver amplifier), volts. Default 0 V."),
      _T("Напруга налаштування, яку код DAC 0 дає на VCO (після підсилювача), вольти. Типово 0 В.") },
    { IDC_EDT_VTUNE_HI, _T("Tuning voltage that DAC code 4095 produces at the VCO, volts. HMC431 tunes 0..10 V. Default 10 V."),
      _T("Напруга налаштування, яку дає код DAC 4095 на VCO, вольти. HMC431 налаштовується 0..10 В. Типово 10 В.") },
    { IDC_EDT_VCO_CURVE, _T("VCO tuning curve as 'Vtune:GHz' points separated by commas, e.g. 0:5.50,1:5.59,...,10:6.10 (HMC431 typical). Linear interpolation between points; replace with values from the datasheet plot or a measurement."),
      _T("Крива налаштування VCO як точки 'Vtune:ГГц' через кому, напр. 0:5.50,1:5.59,...,10:6.10 (типова HMC431). Лінійна інтерполяція між точками; замініть значеннями з графіка даташиту або вимірювання.") },
    { IDC_EDT_F0, _T("Carrier = centre of the sweep, GHz. Sets the wavelength used for velocity (v = lambda * fd / 2) and phase. Read-only while 'f0 / B from tuning curve' is on."),
      _T("Несуча = центр свіпу, ГГц. Задає довжину хвилі для швидкості (v = lambda * fd / 2) і фази. Лише для читання, поки увімкнено 'f0 / B з кривої'.") },
    { IDC_EDT_BW, _T("Swept bandwidth B, MHz. Range = c * T_ramp * f_beat / (2 B); range resolution = c / (2 B). Read-only while derived from the VCO curve."),
      _T("Смуга свіпу B, МГц. Дальність = c * T_ramp * f_beat / (2 B); роздільна здатність = c / (2 B). Лише для читання, поки виводиться з кривої VCO.") },
    { IDC_EDT_TRAMP, _T("Ramp duration override, ms. 0 = automatic from the chirp frequency / firmware header (recommended)."),
      _T("Примусова тривалість рампи, мс. 0 = автоматично з частоти чірпа / заголовка прошивки (рекомендовано).") },
    { IDC_EDT_ROFFSET, _T("Zero-range calibration, m: subtracted from every range (cable and antenna delay). Put a reflector at a known distance and adjust until it reads right. Default 0."),
      _T("Калібрування нульової дальності, м: віднімається від кожної дальності (затримка кабелів і антени). Поставте відбивач на відомій відстані і підберіть значення. Типово 0.") },
    { IDC_CMB_SHAPE, _T("Chirp shape expected in the data. Triangle: each chirp = UP + DOWN ramp (range and velocity from the pair). Sawtooth: UP only. Single: the whole frame is one ramp."),
      _T("Форма чірпа у даних. Трикутник: кожен чірп = рампа UP + DOWN (дальність і швидкість з пари). Пилка: лише UP. Одна рампа: весь кадр одна рампа.") },
    { IDC_CHK_CHIRPS_AUTO, _T("Take the number of chirps per frame from the device burst setting (recommended)."),
      _T("Брати кількість чірпів у кадрі з налаштування burst пристрою (рекомендовано).") },
    { IDC_EDT_CHIRPS, _T("Chirps per frame used by the processing when not taken from the burst setting."),
      _T("Кількість чірпів у кадрі для обробки, коли не береться з burst.") },
    { IDC_EDT_PAIR_V, _T("Largest velocity for which an UP peak and a DOWN peak are still paired as one target, m/s. Larger values pair more aggressively (risk of ghosts). Default 30."),
      _T("Найбільша швидкість, при якій піки UP і DOWN ще спарюються як одна ціль, м/с. Більше значення спарює агресивніше (ризик привидів). Типово 30.") },

    // Settings: application
    { IDC_CHK_DARK, _T("Dark colour theme for every view."), _T("Темна тема для всіх вікон.") },
    { IDC_CMB_LANG, _T("User-interface language. Applied after the application is restarted."), _T("Мова інтерфейсу. Застосовується після перезапуску програми.") },
    { IDC_EDT_FSCAL, _T("Sample rate used when a frame carries none, Hz. Normally the device reports 60 000 000 and this value is not used. Default 60058600."),
      _T("Частота дискретизації, коли кадр її не містить, Гц. Зазвичай пристрій повідомляє 60 000 000 і це значення не використовується. Типово 60058600.") },
    { IDC_EDT_PPM, _T("Correction of the ADC clock in ppm, applied to the sample rate the device reports (frequencies, ranges and the WAV export follow). Measure a known test tone and set ppm = (f_true / f_measured - 1) * 1e6. Default 0."),
      _T("Корекція такту АЦП у ppm, застосовується до частоти, яку повідомляє пристрій (частоти, дальності та експорт WAV слідують). Виміряйте відомий тестовий тон і задайте ppm = (f_true / f_measured - 1) * 1e6. Типово 0.") },
    { IDC_BTN_APPLY_PPM, _T("Apply the ppm correction now (also applied when the field loses focus)."), _T("Застосувати корекцію ppm зараз (також застосовується при втраті фокуса).") },
    { IDC_CHK_VERBOSE, _T("Write a log line for every received frame (useful when debugging the link, noisy otherwise)."),
      _T("Писати рядок журналу для кожного прийнятого кадру (корисно при налагодженні звʼязку, інакше шумно).") },
    { IDC_CHK_AUTOCONNECT, _T("Connect to the first FastAcq port automatically at start-up."), _T("Автоматично підключатися до першого порту FastAcq під час запуску.") },
    { IDC_BTN_SET_RAMP, _T("Send the rise / fall times (CMD_SET_RAMP). With both 0 the symmetric chirp from the frequency is sent instead."),
      _T("Надіслати часи підйому / спаду (CMD_SET_RAMP). Якщо обидва 0, натомість надсилається симетричний чірп з частоти.") },

    // Processing panel
    { IDC_RDO_SRC_RAW, _T("Compute the spectrum on the PC from the raw samples (full processing chain, recommended)."),
      _T("Обчислювати спектр на ПК з сирих відліків (повний ланцюг обробки, рекомендовано).") },
    { IDC_RDO_SRC_MCU, _T("Use the magnitude spectrum computed on the MCU (needs 'FFT' in the frame content). No UP/DOWN pairing, no range-Doppler."),
      _T("Використовувати спектр амплітуд, обчислений на МК (потрібно 'FFT' у вмісті кадру). Без спарювання UP/DOWN і дальність-Доплер.") },
    { IDC_EDT_GUARD, _T("Percentage of each ramp dropped at both ends before the FFT (0..45). The VCO reverses its sweep at the turnaround, so the beat is transient there; 0 uses every sample. Default 5 %."),
      _T("Відсоток кожної рампи, що відкидається з обох кінців перед FFT (0..45). На зламі VCO змінює напрям свіпу, биття там перехідне; 0 використовує всі відліки. Типово 5 %.") },
    { IDC_CHK_DETREND, _T("Remove a linear trend from every ramp (the mean is always removed). Suppresses DC leakage into the first bins. Default on."),
      _T("Прибирати лінійний тренд з кожної рампи (середнє віднімається завжди). Зменшує протікання постійної складової у перші біни. Типово увімкнено.") },
    { IDC_CMB_DECIM, _T("Decimation factor before the FFT. Auto picks the largest factor that keeps the range of interest (plus 25 % margin) below fs/2; a fixed factor overrides it. Decimation does not change the resolution, only the span and speed."),
      _T("Коефіцієнт децимації перед FFT. Авто вибирає найбільший, що тримає дальність інтересу (плюс 25 % запасу) нижче fs/2; фіксований коефіцієнт перекриває. Децимація не змінює роздільну здатність, лише діапазон і швидкість.") },
    { IDC_EDT_MAXRANGE, _T("Range of interest, m: the farthest range the spectrum has to cover (drives the automatic decimation and the default plot span). Zooming out with the wheel on the Radar tab increases it automatically."),
      _T("Дальність інтересу, м: найбільша дальність, яку має покрити спектр (керує автодецимацією і типовим діапазоном графіка). Відкручування колеса на вкладці Радар збільшує її автоматично.") },
    { IDC_CMB_WINDOW, _T("FFT window. Hann: good general choice. Hamming: narrower lobe. Blackman / Blackman-Harris: lowest sidelobes (weak targets next to strong ones). Kaiser: adjustable with beta. Flat-top: exact amplitudes, wide peaks."),
      _T("Вікно FFT. Hann: хороший загальний вибір. Hamming: вужча пелюстка. Blackman / Blackman-Harris: найнижчі бічні пелюстки (слабкі цілі поруч із сильними). Kaiser: регулюється beta. Flat-top: точні амплітуди, широкі піки.") },
    { IDC_EDT_KAISER, _T("Kaiser window shape (only for the Kaiser window): larger beta = lower sidelobes, wider main lobe. 9 is about -70 dB sidelobes."),
      _T("Форма вікна Kaiser (лише для нього): більше beta = нижчі бічні пелюстки, ширша головна. 9 дає близько -70 дБ.") },
    { IDC_CMB_ZEROPAD, _T("Zero padding of the FFT (x1..x8): more points per bin for a smoother plot and finer peak interpolation. Does not improve the true resolution. Default x2."),
      _T("Доповнення FFT нулями (x1..x8): більше точок на бін для гладшого графіка і точнішої інтерполяції піка. Справжню роздільну здатність не покращує. Типово x2.") },
    { IDC_CMB_RANGEGAIN, _T("Tilt applied to the spectrum to compensate the range dependence of the echo power: 20 dB/decade (R^2, point-like) or 40 dB/decade (R^4, radar equation). Off shows the raw levels."),
      _T("Нахил спектра для компенсації залежності потужності луни від дальності: 20 дБ/декаду (R^2, точкова) або 40 дБ/декаду (R^4, рівняння радара). Вимк. показує сирі рівні.") },
    { IDC_CHK_FW_GEOM, _T("Split the frame into chirps and UP/DOWN ramps using the geometry the firmware reports in the frame header (exact samples in protocol v2). Off: frame / chirps / 2. Default on."),
      _T("Ділити кадр на чірпи та рампи UP/DOWN за геометрією, яку прошивка повідомляє в заголовку кадру (точні відліки у протоколі v2). Вимк.: кадр / чірпи / 2. Типово увімкнено.") },
    { IDC_CHK_TONE, _T("Also estimate the strongest tone of each ramp with a dedicated double-precision FFT (Hann ratio interpolation, about 0.5 Hz accuracy); shown on the Scope tab."),
      _T("Додатково оцінювати найсильніший тон кожної рампи окремим FFT подвійної точності (інтерполяція Hann, точність близько 0.5 Гц); показується на вкладці Осцилограф.") },
    { IDC_CMB_DETECTOR, _T("How the detection threshold is formed. Noise floor + X dB: fixed margin above the median. CA-CFAR: mean of neighbouring cells. OS-CFAR: ordered statistic, robust to nearby targets. GO-CFAR: fewer false alarms at clutter edges. SO-CFAR: keeps targets next to clutter edges."),
      _T("Як формується поріг виявлення. Шум + X дБ: фіксований запас над медіаною. CA-CFAR: середнє сусідніх комірок. OS-CFAR: порядкова статистика, стійка до сусідніх цілей. GO-CFAR: менше хибних тривог на краях завад. SO-CFAR: зберігає цілі біля країв завад.") },
    { IDC_EDT_THRESH, _T("Margin above the noise estimate for the 'Noise floor + X dB' detector, dB. Default 12."),
      _T("Запас над оцінкою шуму для детектора 'Шум + X дБ', дБ. Типово 12.") },
    { IDC_CMB_PFA, _T("Probability that a noise-only cell is reported as a target by the CFAR detectors. Smaller = higher threshold, fewer false alarms, weaker targets lost. Default 0.0001."),
      _T("Ймовірність того, що комірка лише з шумом буде визнана ціллю детекторами CFAR. Менше = вищий поріг, менше хибних тривог, слабкі цілі губляться. Типово 0.0001.") },
    { IDC_EDT_CFAR_GUARD, _T("Cells next to the cell under test that are excluded from the noise estimate (so the target's own energy does not raise the threshold). Set to about the peak width in bins. Default 2."),
      _T("Комірки поруч із перевірюваною, виключені з оцінки шуму (щоб енергія самої цілі не піднімала поріг). Приблизно ширина піка у бінах. Типово 2.") },
    { IDC_EDT_CFAR_TRAIN, _T("Cells on each side used for the noise estimate. More cells = steadier threshold but slower to follow a changing noise floor. Default 16."),
      _T("Комірки з кожного боку для оцінки шуму. Більше комірок = стабільніший поріг, але повільніше слідування за шумом. Типово 16.") },
    { IDC_CMB_INTERP, _T("Sub-bin interpolation of the peak frequency. Parabolic (dB): works with every window. Jacobsen / Candan / Quinn: complex-bin estimators, most accurate with a rectangular window."),
      _T("Субінтерполяція частоти піка. Парабола (дБ): працює з будь-яким вікном. Jacobsen / Candan / Quinn: оцінювачі по комплексних бінах, найточніші з прямокутним вікном.") },
    { IDC_EDT_MAXPEAKS, _T("Maximum number of targets reported per frame (strongest first), 1..64. Default 10."),
      _T("Максимум цілей на кадр (спочатку найсильніші), 1..64. Типово 10.") },
    { IDC_CHK_MTI, _T("Range-Doppler map: subtract the mean over the chirps so static clutter disappears and only moving targets remain. Default on."),
      _T("Карта дальність-Доплер: віднімати середнє по чірпах, щоб нерухомі завади зникли і лишилися рухомі цілі. Типово увімкнено.") },
    { IDC_CHK_TRACK, _T("Nearest-neighbour tracking across frames so a target keeps the same ID (needed for the confirmation filter). Default on."),
      _T("Супровід найближчого сусіда між кадрами, щоб ціль зберігала той самий ID (потрібно для фільтра підтвердження). Типово увімкнено.") },
    { IDC_CHK_HARMONICS, _T("Drop peaks that sit at 2f, 3f, ... 5f of a stronger peak and are weaker by at least the dB below: mixer and ADC nonlinearity create such copies of a strong beat tone. Default off."),
      _T("Відкидати піки на 2f, 3f, ... 5f від сильнішого піка, слабші щонайменше на вказані дБ: нелінійність змішувача та АЦП створює такі копії сильного тону биття. Типово вимк.") },
    { IDC_EDT_HARM_DROP, _T("A harmonic candidate must be at least this much weaker than its fundamental to be dropped, dB. Default 6."),
      _T("Кандидат у гармоніки має бути слабшим за основний тон щонайменше на стільки дБ, щоб бути відкинутим. Типово 6.") },
    { IDC_EDT_MIN_SNR, _T("Peaks with SNR below this value are not reported, dB. 0 = off."),
      _T("Піки з SNR нижче цього значення не повідомляються, дБ. 0 = вимк.") },
    { IDC_EDT_CONFIRM, _T("A target is listed only after its track has been seen in this many consecutive frames (0 or 1 = immediately). Suppresses one-frame false alarms at the cost of a short delay."),
      _T("Ціль показується лише після того, як її трек бачили стільки кадрів поспіль (0 або 1 = одразу). Прибирає однокадрові хибні тривоги ціною невеликої затримки.") },
    { IDC_EDT_SPURS, _T("Frequency bands to ignore as 'centre:halfwidth' in Hz, comma separated, e.g. 1000000:2000, 2500000. Omitted half width = 2000 Hz. Use for clock leakage, supply spurs or a fixed reflection."),
      _T("Смуги частот, які ігноруються, у вигляді 'центр:півширина' у Гц через кому, напр. 1000000:2000, 2500000. Пропущена півширина = 2000 Гц. Для протікання тактів, завад живлення або фіксованого відбиття.") },
    { IDC_BTN_LEARN_SPURS, _T("Add every peak detected in the current frame to the spur mask. Use it with nothing in front of the antenna so the fixed spurious lines are masked afterwards."),
      _T("Додати всі піки, виявлені в поточному кадрі, до маски завад. Використовуйте, коли перед антеною нічого немає, щоб далі фіксовані завади ігнорувалися.") },
    { IDC_BTN_CLEAR_SPURS, _T("Empty the spur mask."), _T("Очистити маску завад.") },
    { IDC_EDT_DBTOP, _T("Top of the dB axis on the range profile and the colour scale, dBFS (0 = full-scale sine). Default 0."),
      _T("Верх осі дБ на профілі дальності та шкали кольорів, дБFS (0 = синус повної шкали). Типово 0.") },
    { IDC_EDT_DBBOTTOM, _T("Bottom of the dB axis, dBFS. Default -120."), _T("Низ осі дБ, дБFS. Типово -120.") },
    { IDC_EDT_WF_ROWS, _T("History depth of the waterfall in frames (64..4096). Default 512."), _T("Глибина історії водоспаду у кадрах (64..4096). Типово 512.") },
    { IDC_EDT_ADCBITS, _T("ADC resolution used to scale codes to volts on the Scope tab. Default 12."), _T("Розрядність АЦП для перерахунку кодів у вольти на вкладці Осцилограф. Типово 12.") },
    { IDC_EDT_VREF, _T("ADC full-scale voltage for the volts scale on the Scope tab. Default 3.3 V."), _T("Напруга повної шкали АЦП для шкали вольтів на вкладці Осцилограф. Типово 3.3 В.") },
    { IDC_BTN_DEFAULTS, _T("Reset the processing, detection and display settings of this column to their defaults (MCU and radar settings are kept)."),
      _T("Скинути налаштування обробки, виявлення та відображення цієї колонки до типових (налаштування МК і радара зберігаються).") },

    // Radar footer
    { IDC_CMB_TRACE, _T("Trace mode of the spectrum. Clear write: every frame as is. Average: exponential average (steadier noise floor). Max hold / Min hold: envelope over time."),
      _T("Режим траси спектра. Clear write: кожен кадр як є. Average: експоненційне усереднення (стабільніший шум). Max hold / Min hold: огинаюча в часі.") },
    { IDC_CMB_WF_PALETTE, _T("Colour palette of the waterfall and the range-Doppler map."), _T("Палітра кольорів водоспаду та карти дальність-Доплер.") },
    { IDC_CHK_SHOW_UP, _T("Show the UP-ramp spectrum."), _T("Показувати спектр рампи UP.") },
    { IDC_CHK_SHOW_DN, _T("Show the DOWN-ramp spectrum."), _T("Показувати спектр рампи DOWN.") },
    { IDC_CHK_SHOW_THR, _T("Show the detection threshold line."), _T("Показувати лінію порога виявлення.") },
    { IDC_CHK_SHOW_NOISE, _T("Show the noise estimate line."), _T("Показувати лінію оцінки шуму.") },
    { IDC_CHK_SHOW_RD, _T("Show the range-Doppler map next to the waterfall (needs more than one chirp per frame)."), _T("Показувати карту дальність-Доплер поруч із водоспадом (потрібно більше одного чірпа в кадрі).") },
    { IDC_BTN_RESET_AVG, _T("Restart the trace averaging, phase accumulation and tracks. Key: A."), _T("Перезапустити усереднення траси, накопичення фази та треки. Клавіша: A.") },
    { IDC_BTN_AUTOSCALE, _T("Fit the dB axis and the colour scale to the current data."), _T("Підігнати вісь дБ і шкалу кольорів під поточні дані.") },
    { IDC_BTN_CLEAR_WF, _T("Clear the waterfall history."), _T("Очистити історію водоспаду.") },

    // Scope footer
    { IDC_CHK_DOTS, _T("Draw individual samples as dots instead of a line."), _T("Малювати окремі відліки точками замість лінії.") },
    { IDC_RDO_VOLTS, _T("Vertical scale in volts (ADC bits and full scale from the Radar tab settings)."), _T("Вертикальна шкала у вольтах (розрядність і повна шкала з налаштувань на вкладці Радар).") },
    { IDC_RDO_CODES, _T("Vertical scale in raw ADC codes."), _T("Вертикальна шкала у сирих кодах АЦП.") },
    { IDC_CMB_RAMP_SEL, _T("Which ramp of the frame is shown in the detail view below."), _T("Яка рампа кадру показується у деталі нижче.") },

    // Communication footer
    { IDC_CMB_LOG_FILTER, _T("Show only log lines of one kind."), _T("Показувати лише рядки журналу одного типу.") },
    { IDC_CHK_LOG_VERBOSE, _T("Log every received frame (one line per frame)."), _T("Записувати кожен прийнятий кадр (рядок на кадр).") },
    { IDC_CHK_LOG_SCROLL, _T("Keep the newest line in view."), _T("Тримати найновіший рядок у полі зору.") },
    { IDC_BTN_LOG_COPY, _T("Copy the selected lines (or all) to the clipboard."), _T("Копіювати вибрані рядки (або всі) у буфер обміну.") },
    { IDC_BTN_LOG_SAVE, _T("Save the log to a text file."), _T("Зберегти журнал у текстовий файл.") },
    { IDC_BTN_LOG_CLEAR, _T("Clear the log."), _T("Очистити журнал.") },

    // Trace tab
    { IDC_TRC_CHK_ENABLE, _T("Enable the acquisition trace inside the firmware (CMD_SET_TRACE). Each capture then sends a TRACE frame with its step-by-step timeline."),
      _T("Увімкнути трасування захоплення у прошивці (CMD_SET_TRACE). Кожне захоплення тоді надсилає TRACE-кадр із покроковою хронологією.") },
    { IDC_TRC_BTN_SHOT, _T("Switch the device to SINGLE mode and trigger one capture (one traced cycle)."), _T("Перевести пристрій у режим SINGLE і зробити одне захоплення (один трасований цикл).") },
    { IDC_TRC_BTN_GET, _T("Ask the device to send its trace buffer now (CMD_GET_TRACE)."), _T("Попросити пристрій надіслати буфер трасування зараз (CMD_GET_TRACE).") },
    { IDC_TRC_BTN_CLEAR, _T("Clear the trace list."), _T("Очистити список траси.") },
    { IDC_TRC_BTN_EXPORT, _T("Export the trace records to a CSV file."), _T("Експортувати записи траси у файл CSV.") },
};

std::map<CString, CString>& Table()
{
    static std::map<CString, CString> t;
    if (t.empty()) for (const auto& e : kStrings) t[e.en] = e.uk;
    return t;
}

} // namespace

void Set(Id id) { g_lang = (id == Id::Ukrainian) ? Id::Ukrainian : Id::English; }
Id   Get()      { return g_lang; }

LPCTSTR Name(Id id) { return id == Id::Ukrainian ? _T("Українська") : _T("English"); }

CString Tr(LPCTSTR english)
{
    if (!english) return CString();
    if (g_lang == Id::English) return CString(english);
    const auto& t = Table();
    auto it = t.find(CString(english));
    return (it != t.end()) ? it->second : CString(english);
}

CString Help(UINT ctrlId)
{
    for (const auto& h : kHelp)
        if (h.id == ctrlId) return CString(g_lang == Id::Ukrainian ? h.uk : h.en);
    return CString();
}

void TranslateMenu(CMenu* menu)
{
    if (!menu || !menu->GetSafeHmenu()) return;
    const UINT n = menu->GetMenuItemCount();
    for (UINT i = 0; i < n; ++i) {
        CString text;
        menu->GetMenuString(i, text, MF_BYPOSITION);
        if (text.IsEmpty()) continue;
        const CString tr = Tr(text);
        CMenu* sub = menu->GetSubMenu(static_cast<int>(i));
        if (sub) {
            if (tr != text) menu->ModifyMenu(i, MF_BYPOSITION | MF_STRING | MF_POPUP, reinterpret_cast<UINT_PTR>(sub->GetSafeHmenu()), tr);
            TranslateMenu(sub);
        } else {
            const UINT id = menu->GetMenuItemID(static_cast<int>(i));
            if (tr != text && id != static_cast<UINT>(-1)) menu->ModifyMenu(i, MF_BYPOSITION | MF_STRING, id, tr);
        }
    }
}

} // namespace Lang
